# typed: strong
# frozen_string_literal: true

require "fileutils"
require "pathname"
require "shellwords"
require "sorbet-runtime"

require "dependabot/gradle/file_updater"

module Dependabot
  module Gradle
    class FileUpdater
      class LockfileUpdater
        extend T::Sig

        INIT_SCRIPT_TASK_NAME = T.let("dependabotResolveAll", String)

        sig { params(dependency_files: T::Array[Dependabot::DependencyFile]).void }
        def initialize(dependency_files:)
          @dependency_files = dependency_files
        end

        sig { params(build_file: Dependabot::DependencyFile).returns(T::Array[Dependabot::DependencyFile]) }
        def update_lockfiles(build_file)
          root_dir = determine_root_dir(build_file: build_file)
          lockfiles = lockfiles_for_root(root_dir)

          return dependency_files unless lockfiles.any?

          updated_files = dependency_files.dup

          SharedHelpers.in_a_temporary_directory do |temp_dir|
            populate_temp_directory(temp_dir)

            cwd = File.join(temp_dir, root_dir == "/" ? "" : root_dir.delete_prefix("/"))
            FileUtils.mkdir_p(cwd)

            write_properties_file(File.join(cwd, "gradle.properties"))

            init_script_path = File.join(cwd, "dependabot-locking.init.gradle")
            write_init_script(init_script_path)

            command_parts = [
              gradle_executable_for(cwd),
              "--init-script", init_script_path,
              INIT_SCRIPT_TASK_NAME,
              "--write-locks",
              "--no-daemon"
            ]
            run_lockfile_update_command(command_parts: command_parts, cwd: cwd)

            update_lockfiles_content(temp_dir, lockfiles, updated_files)
          rescue SharedHelpers::HelperSubprocessFailed => e
            Dependabot.logger.error("Failed to update lockfiles: #{e.message}")
            return updated_files
          end

          updated_files
        end

        sig { params(build_file: Dependabot::DependencyFile).returns(String) }
        def determine_root_dir(build_file:)
          settings_file = find_settings_file(build_file)
          return normalized_directory_path(settings_file) if settings_file

          file_path = normalized_file_path(build_file)
          return normalize_path(File.dirname(file_path, 2)) if file_path.end_with?("/gradle/libs.versions.toml")

          normalized_directory_path(build_file)
        end

        sig { params(file: Dependabot::DependencyFile).returns(String) }
        def normalized_directory_path(file)
          file_path = normalized_file_path(file)
          dir = File.dirname(file_path)
          dir == "/" ? "/" : normalize_path(dir)
        end

        sig { params(root_dir: String).returns(T::Array[Dependabot::DependencyFile]) }
        def lockfiles_for_root(root_dir)
          sub_build_roots = sub_build_roots_for(root_dir)

          dependency_files.select do |file|
            next false unless file.name.end_with?(".lockfile")

            file_path = normalized_file_path(file)
            next false unless path_under_root?(file_path, root_dir)

            sub_build_roots.none? { |sub_root| file_path.start_with?("#{sub_root}/") || file_path == sub_root }
          end
        end

        sig do
          params(
            temp_dir: T.any(Pathname, String),
            lockfiles: T::Array[Dependabot::DependencyFile],
            updated_lockfiles: T::Array[Dependabot::DependencyFile]
          ).void
        end
        def update_lockfiles_content(temp_dir, lockfiles, updated_lockfiles)
          lockfiles.each do |file|
            # Handle "/" directory as root - File.join treats "/" as absolute path and ignores prior components
            relative_dir = file.directory == "/" ? "" : file.directory
            lockfile_path = File.join(temp_dir, relative_dir, file.name)

            unless File.exist?(lockfile_path)
              Dependabot.logger.warn(
                "Lockfile #{file.name} was not regenerated by Gradle after a successful lockfile update run. " \
                "Preserving existing lockfile."
              )
              next
            end

            content = File.read(lockfile_path)
            next if content == file.content

            tmp_file = file.dup
            tmp_file.content = content

            index = updated_lockfiles.find_index { |f| f.name == file.name }
            if index
              updated_lockfiles[index] = tmp_file
            else
              updated_lockfiles << tmp_file
            end
          end
        end

        private

        sig { returns(T::Array[Dependabot::DependencyFile]) }
        attr_reader :dependency_files

        sig { params(file_path: String, root_dir: String).returns(T::Boolean) }
        def path_under_root?(file_path, root_dir)
          root_dir == "/" || file_path == root_dir || file_path.start_with?("#{root_dir}/")
        end

        # Find all sub-build roots (settings files deeper than root_dir) so we can
        # exclude lockfiles that belong to an included/composite build.
        sig { params(root_dir: String).returns(T::Array[String]) }
        def sub_build_roots_for(root_dir)
          dependency_files.filter_map do |f|
            basename = File.basename(f.name)
            next unless basename == "settings.gradle" || basename == "settings.gradle.kts"

            dir = normalized_directory_path(f)
            next if dir == root_dir

            dir if path_under_root?(dir, root_dir)
          end
        end

        sig { params(file: Dependabot::DependencyFile).returns(String) }
        def normalized_file_path(file)
          # Handle "/" directory as root - File.join treats "/" as absolute path and ignores prior components
          relative_dir = file.directory == "/" ? "" : file.directory
          path = relative_dir.empty? ? file.name : File.join(relative_dir, file.name)
          normalize_path(path)
        end

        sig { params(path: String).returns(String) }
        def normalize_path(path)
          normalized = path.squeeze("/")
          normalized = "/#{normalized}" unless normalized.start_with?("/")
          normalized = normalized.sub(%r{/$}, "")
          normalized.empty? ? "/" : normalized
        end

        sig { params(temp_dir: T.any(Pathname, String)).void }
        def populate_temp_directory(temp_dir)
          @dependency_files.each do |file|
            # Handle "/" directory as root - File.join treats "/" as absolute path and ignores prior components
            relative_dir = file.directory == "/" ? "" : file.directory
            in_path_name = File.join(temp_dir, relative_dir, file.name)
            FileUtils.mkdir_p(File.dirname(in_path_name))
            File.binwrite(in_path_name, file.decoded_content)
          end
        end

        sig { params(file_name: String).void }
        def write_properties_file(file_name) # rubocop:disable Metrics/PerceivedComplexity
          http_proxy = ENV.fetch("HTTP_PROXY", nil)
          https_proxy = ENV.fetch("HTTPS_PROXY", nil)
          http_split = http_proxy&.split(":")
          https_split = https_proxy&.split(":")
          http_proxy_host = http_split&.fetch(1, nil)&.gsub("//", "") || "host.docker.internal"
          https_proxy_host = https_split&.fetch(1, nil)&.gsub("//", "") || "host.docker.internal"
          http_proxy_port = http_split&.fetch(2) || "1080"
          https_proxy_port = https_split&.fetch(2) || "1080"

          existing_content = File.exist?(file_name) ? File.read(file_name) : ""

          proxy_properties = "
systemProp.http.proxyHost=#{http_proxy_host}
systemProp.http.proxyPort=#{http_proxy_port}
systemProp.https.proxyHost=#{https_proxy_host}
systemProp.https.proxyPort=#{https_proxy_port}"

          separator = !existing_content.empty? && !existing_content.end_with?("\n") ? "\n" : ""
          File.write(file_name, existing_content + separator + proxy_properties)
        end

        sig { params(file_name: String).void }
        def write_init_script(file_name)
          # Resolve all resolvable configurations across all loaded projects so
          # Gradle rewrites every relevant lockfile in one invocation.
          script_content = <<~GRADLE
            allprojects {
              if (tasks.findByName("#{INIT_SCRIPT_TASK_NAME}") == null) {
                tasks.register("#{INIT_SCRIPT_TASK_NAME}") {
                  doLast {
                    configurations.findAll { it.canBeResolved }.each { it.resolve() }
                  }
                }
              }
            }
          GRADLE
          File.write(file_name, script_content)
        end

        sig { params(cwd: String).returns(String) }
        def gradle_executable_for(cwd)
          cwd_path = Pathname.new(cwd)
          search_path = cwd_path

          loop do
            wrapper_script = search_path.join("gradlew")
            if File.file?(wrapper_script)
              wrapper_script_path = wrapper_script.to_s
              FileUtils.chmod("+x", wrapper_script_path)

              relative_path = wrapper_script.relative_path_from(cwd_path).to_s
              return relative_path.start_with?(".") ? relative_path : "./#{relative_path}"
            end

            parent_path = search_path.parent
            break if parent_path == search_path

            search_path = parent_path
          end

          "gradle"
        end

        sig { params(command_parts: T::Array[String], cwd: String).void }
        def run_lockfile_update_command(command_parts:, cwd:)
          command = Shellwords.join(command_parts)
          SharedHelpers.run_shell_command(command, cwd: cwd)
        rescue SharedHelpers::HelperSubprocessFailed => e
          raise e unless local_wrapper_command?(command_parts[0])

          display_command = command_parts.join(" ")
          Dependabot.logger.warn("Running #{display_command} failed, retrying with system Gradle: #{e.message}")

          fallback_command = Shellwords.join(["gradle"] + command_parts.drop(1))
          SharedHelpers.run_shell_command(fallback_command, cwd: cwd)
        end

        sig { params(executable: String).returns(T::Boolean) }
        def local_wrapper_command?(executable)
          executable != "gradle" && File.basename(executable) == "gradlew"
        end

        sig { params(build_file: Dependabot::DependencyFile).returns(T.nilable(Dependabot::DependencyFile)) }
        def find_settings_file(build_file)
          settings_files = dependency_files.select do |f|
            basename = File.basename(f.name)
            basename == "settings.gradle" || basename == "settings.gradle.kts"
          end

          return nil if settings_files.empty?

          build_dir = normalized_directory_path(build_file)

          ancestor_settings = settings_files.select do |f|
            settings_dir = normalized_directory_path(f)
            path_under_root?(build_dir, settings_dir)
          end

          return nil if ancestor_settings.empty?

          ancestor_settings.max_by do |f|
            normalized_directory_path(f).split("/").count { |element| !element.empty? }
          end
        end
      end
    end
  end
end
