#!/bin/bash

set -e

if [ -z "$DEPENDABOT_NATIVE_HELPERS_PATH" ]; then
  echo "Unable to build, DEPENDABOT_NATIVE_HELPERS_PATH is not set"
  exit 1
fi

install_dir="$DEPENDABOT_NATIVE_HELPERS_PATH/bundler/v2"
mkdir -p "$install_dir"

helpers_dir="$(dirname "${BASH_SOURCE[0]}")"
cp -r \
  "$helpers_dir/lib" \
  "$helpers_dir/monkey_patches" \
  "$helpers_dir/run.rb" \
  "$helpers_dir/Gemfile" \
  "$install_dir"

cd "$install_dir"

bundle config --local path ".bundle"
bundle config --local without "test"
bundle install
