inherit_from: ../.rubocop.yml

inherit_mode:
  merge:
    - Exclude

Sorbet/StrictSigil:
  Exclude:
    - lib/dependabot/cargo/file_fetcher.rb
    - lib/dependabot/cargo/file_parser.rb
    - lib/dependabot/cargo/file_updater/lockfile_updater.rb
    - lib/dependabot/cargo/file_updater/manifest_updater.rb
    - lib/dependabot/cargo/file_updater.rb
    - lib/dependabot/cargo/helpers.rb
    - lib/dependabot/cargo/metadata_finder.rb
    - lib/dependabot/cargo/registry_fetcher.rb
    - lib/dependabot/cargo/requirement.rb
    - lib/dependabot/cargo/update_checker/file_preparer.rb
    - lib/dependabot/cargo/update_checker/requirements_updater.rb
    - lib/dependabot/cargo/update_checker/version_resolver.rb
    - lib/dependabot/cargo/update_checker.rb
    - lib/dependabot/cargo/version.rb
