# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `docker_registry2` gem.
# Please instead update this file by running `bin/tapioca gem docker_registry2`.


# pkg:gem/docker_registry2#lib/registry/version.rb:3
module DockerRegistry2
  class << self
    # pkg:gem/docker_registry2#lib/docker_registry2.rb:10
    def connect(uri = T.unsafe(nil), opts = T.unsafe(nil)); end

    # pkg:gem/docker_registry2#lib/docker_registry2.rb:22
    def manifest(repository, tag); end

    # pkg:gem/docker_registry2#lib/docker_registry2.rb:26
    def manifest_digest(repository, tag); end

    # pkg:gem/docker_registry2#lib/docker_registry2.rb:14
    def search(query = T.unsafe(nil)); end

    # pkg:gem/docker_registry2#lib/docker_registry2.rb:18
    def tags(repository); end
  end
end

# pkg:gem/docker_registry2#lib/registry/blob.rb:4
class DockerRegistry2::Blob
  # pkg:gem/docker_registry2#lib/registry/blob.rb:7
  def initialize(headers, body); end

  # pkg:gem/docker_registry2#lib/registry/blob.rb:5
  def body; end

  # pkg:gem/docker_registry2#lib/registry/blob.rb:5
  def headers; end
end

# pkg:gem/docker_registry2#lib/registry/exceptions.rb:4
class DockerRegistry2::Exception < ::RuntimeError; end

# pkg:gem/docker_registry2#lib/registry/exceptions.rb:31
class DockerRegistry2::InvalidMethod < ::DockerRegistry2::Exception; end

# Manifest class represents a manfiest or index in an OCI registry
#
# pkg:gem/docker_registry2#lib/registry/manifest.rb:5
class DockerRegistry2::Manifest < ::Hash
  # pkg:gem/docker_registry2#lib/registry/manifest.rb:6
  def body; end

  # pkg:gem/docker_registry2#lib/registry/manifest.rb:6
  def body=(_arg0); end

  # pkg:gem/docker_registry2#lib/registry/manifest.rb:6
  def headers; end

  # pkg:gem/docker_registry2#lib/registry/manifest.rb:6
  def headers=(_arg0); end
end

# pkg:gem/docker_registry2#lib/registry/exceptions.rb:28
class DockerRegistry2::NotFound < ::DockerRegistry2::Exception; end

# pkg:gem/docker_registry2#lib/registry/exceptions.rb:22
class DockerRegistry2::ReauthenticatedException < ::DockerRegistry2::Exception; end

# pkg:gem/docker_registry2#lib/registry/registry.rb:14
class DockerRegistry2::Registry
  # @param [#to_s] base_uri Docker registry base URI
  # @param [Hash] options Client options
  # @option options [#to_s] :user User name for basic authentication
  # @option options [#to_s] :password Password for basic authentication
  # @option options [#to_s] :open_timeout Time to wait for a connection with a registry.
  #                                       It is ignored if http_options[:open_timeout] is also specified.
  # @option options [#to_s] :read_timeout Time to wait for data from a registry.
  #                                       It is ignored if http_options[:read_timeout] is also specified.
  # @option options [Hash] :http_options Extra options for Faraday connection/request setup.
  #
  # pkg:gem/docker_registry2#lib/registry/registry.rb:24
  def initialize(uri, options = T.unsafe(nil)); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:211
  def _pull_v1(repo, manifest, dir); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:193
  def _pull_v2(repo, manifest, dir); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:125
  def blob(repo, digest, outpath = T.unsafe(nil)); end

  # gets the size of a particular blob, given the repo and the content-addressable hash
  # usually unneeded, since manifest includes it
  #
  # pkg:gem/docker_registry2#lib/registry/registry.rb:244
  def blob_size(repo, blobSum); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:240
  def copy(repo, tag, newregistry, newrepo, newtag); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:147
  def digest(image, tag, architecture = T.unsafe(nil), os = T.unsafe(nil), variant = T.unsafe(nil)); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:44
  def dodelete(url); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:36
  def doget(url, accept: T.unsafe(nil)); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:48
  def dohead(url); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:40
  def doput(url, payload = T.unsafe(nil)); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:266
  def last(header); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:115
  def manifest(repo, tag); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:139
  def manifest_digest(repo, tag); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:275
  def manifest_sum(manifest); end

  # When a result set is too large, the Docker registry returns only the first items and adds a Link header in the
  # response with the URL of the next page. See <https://docs.docker.com/registry/spec/api/#pagination>. This method
  # iterates over the pages and calls the given block with each response.
  #
  # pkg:gem/docker_registry2#lib/registry/registry.rb:55
  def paginate_doget(url); end

  # Parse the value of the Link HTTP header and return a Hash whose keys are the rel values turned into symbols, and
  # the values are URLs. For example, `{ next: '/v2/_catalog?n=100&last=x' }`.
  #
  # pkg:gem/docker_registry2#lib/registry/registry.rb:251
  def parse_link_header(header); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:179
  def pull(repo, tag, dir); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:230
  def push(manifest, dir); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:172
  def rmtag(image, tag); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:69
  def search(query = T.unsafe(nil)); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:232
  def tag(repo, tag, newrepo, newtag); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:79
  def tags(repo, count = T.unsafe(nil), last = T.unsafe(nil), withHashes = T.unsafe(nil), auto_paginate: T.unsafe(nil)); end

  private

  # pkg:gem/docker_registry2#lib/registry/registry.rb:491
  def apply_auth!(request, auth); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:430
  def apply_timeout_defaults(options); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:317
  def authenticate_bearer(header); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:374
  def build_connection(base_url); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:370
  def connection; end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:383
  def connection_options; end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:355
  def default_accept_header; end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:301
  def do_basic_req(type, url, stream = T.unsafe(nil), payload = T.unsafe(nil), **request_options); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:306
  def do_bearer_req(type, url, header, request_options = T.unsafe(nil)); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:547
  def doget_with_legacy_fallback(url); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:285
  def doreq(type, url, stream = T.unsafe(nil), payload = T.unsafe(nil), **request_options); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:530
  def handle_error_response(response, unauthorized_exception:, forbidden_exception: T.unsafe(nil)); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:346
  def headers(payload: T.unsafe(nil), bearer_token: T.unsafe(nil), accept: T.unsafe(nil)); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:363
  def legacy_manifest_accept_header; end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:451
  def load_client_certificate(path); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:455
  def load_client_key(path); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:521
  def normalize_headers(raw_headers); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:446
  def normalize_legacy_client_cert_paths!(ssl); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:435
  def normalize_legacy_verify_ssl!(ssl, options); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:512
  def normalize_response(response, stream: T.unsafe(nil)); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:403
  def normalize_ssl_options(options); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:474
  def perform(conn, type, url, request_options = T.unsafe(nil)); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:467
  def perform_absolute_request(type, url, request_options = T.unsafe(nil)); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:463
  def perform_request(type, url, request_options = T.unsafe(nil)); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:396
  def request_options(request = T.unsafe(nil)); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:333
  def split_auth_header(header = T.unsafe(nil)); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:418
  def ssl_aliases; end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:505
  def stream_handler(stream); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:459
  def symbolize_keys(hash); end
end

# pkg:gem/docker_registry2#lib/registry/exceptions.rb:7
class DockerRegistry2::RegistryAuthenticationException < ::DockerRegistry2::Exception; end

# pkg:gem/docker_registry2#lib/registry/exceptions.rb:10
class DockerRegistry2::RegistryAuthorizationException < ::DockerRegistry2::Exception; end

# pkg:gem/docker_registry2#lib/registry/exceptions.rb:34
class DockerRegistry2::RegistryHTTPException < ::DockerRegistry2::Exception; end

# pkg:gem/docker_registry2#lib/registry/exceptions.rb:16
class DockerRegistry2::RegistrySSLException < ::DockerRegistry2::Exception; end

# pkg:gem/docker_registry2#lib/registry/exceptions.rb:13
class DockerRegistry2::RegistryUnknownException < ::DockerRegistry2::Exception; end

# pkg:gem/docker_registry2#lib/registry/exceptions.rb:19
class DockerRegistry2::RegistryVersionException < ::DockerRegistry2::Exception; end

# pkg:gem/docker_registry2#lib/registry/registry.rb:12
class DockerRegistry2::Response < ::Struct
  # pkg:gem/docker_registry2#lib/registry/registry.rb:12
  def body; end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:12
  def body=(_); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:12
  def code; end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:12
  def code=(_); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:12
  def headers; end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:12
  def headers=(_); end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:12
  def request_url; end

  # pkg:gem/docker_registry2#lib/registry/registry.rb:12
  def request_url=(_); end

  class << self
    # pkg:gem/docker_registry2#lib/registry/registry.rb:12
    def [](*_arg0); end

    # pkg:gem/docker_registry2#lib/registry/registry.rb:12
    def inspect; end

    # pkg:gem/docker_registry2#lib/registry/registry.rb:12
    def keyword_init?; end

    # pkg:gem/docker_registry2#lib/registry/registry.rb:12
    def members; end

    # pkg:gem/docker_registry2#lib/registry/registry.rb:12
    def new(*_arg0); end
  end
end

# pkg:gem/docker_registry2#lib/registry/exceptions.rb:25
class DockerRegistry2::UnknownRegistryException < ::DockerRegistry2::Exception; end

# pkg:gem/docker_registry2#lib/registry/version.rb:4
DockerRegistry2::VERSION = T.let(T.unsafe(nil), String)
