# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `excon` gem.
# Please instead update this file by running `bin/tapioca gem excon`.


# Define defaults first so they will be available to other files
#
# pkg:gem/excon#lib/excon/version.rb:3
module Excon
  class << self
    # pkg:gem/excon#lib/excon.rb:254
    def connect(url, params = T.unsafe(nil), &block); end

    # @return [Hash] defaults for Excon connections
    # Change defaults for Excon connections
    # @return [Hash] defaults for Excon connections
    #
    # pkg:gem/excon#lib/excon.rb:54
    def defaults; end

    # @return [Hash] defaults for Excon connections
    # Change defaults for Excon connections
    # @return [Hash] defaults for Excon connections
    #
    # pkg:gem/excon#lib/excon.rb:60
    def defaults=(_arg0); end

    # pkg:gem/excon#lib/excon.rb:254
    def delete(url, params = T.unsafe(nil), &block); end

    # pkg:gem/excon#lib/excon.rb:62
    def display_warning(warning); end

    # pkg:gem/excon#lib/excon.rb:254
    def get(url, params = T.unsafe(nil), &block); end

    # pkg:gem/excon#lib/excon.rb:254
    def head(url, params = T.unsafe(nil), &block); end

    # Status of mocking
    #
    # pkg:gem/excon#lib/excon.rb:76
    def mock; end

    # Change the status of mocking
    # false is the default and works as expected
    # true returns a value from stubs or raises
    #
    # pkg:gem/excon#lib/excon.rb:84
    def mock=(new_mock); end

    # @see Connection#initialize
    # Initializes a new keep-alive session for a given remote host
    # @param [String] url The destination URL
    # @param [Hash<Symbol, >] params One or more option params to set on the Connection instance
    # @return [Connection] A new Excon::Connection instance
    #
    # pkg:gem/excon#lib/excon.rb:120
    def new(url, params = T.unsafe(nil)); end

    # pkg:gem/excon#lib/excon.rb:254
    def options(url, params = T.unsafe(nil), &block); end

    # pkg:gem/excon#lib/excon.rb:254
    def patch(url, params = T.unsafe(nil), &block); end

    # pkg:gem/excon#lib/excon.rb:254
    def post(url, params = T.unsafe(nil), &block); end

    # pkg:gem/excon#lib/excon.rb:254
    def put(url, params = T.unsafe(nil), &block); end

    # pkg:gem/excon#lib/excon.rb:71
    def set_raise_on_warnings!(should_raise); end

    # @return [String] The filesystem path to the SSL Certificate Authority
    #
    # pkg:gem/excon#lib/excon.rb:90
    def ssl_ca_path; end

    # Change path to the SSL Certificate Authority
    # @return [String] The filesystem path to the SSL Certificate Authority
    #
    # pkg:gem/excon#lib/excon.rb:97
    def ssl_ca_path=(new_ssl_ca_path); end

    # @return [true, false] Whether or not to verify the peer's SSL certificate / chain
    #
    # pkg:gem/excon#lib/excon.rb:103
    def ssl_verify_peer; end

    # Change the status of ssl peer verification
    # @see Excon#ssl_verify_peer (attr_reader)
    #
    # pkg:gem/excon#lib/excon.rb:110
    def ssl_verify_peer=(new_ssl_verify_peer); end

    # push an additional stub onto the list to check for mock requests
    # @param request_params [Hash<Symbol, >] request params to match against, omitted params match all
    # @param response_params [Hash<Symbol, >] response params to return or block to call with matched params
    #
    # pkg:gem/excon#lib/excon.rb:142
    def stub(request_params = T.unsafe(nil), response_params = T.unsafe(nil), &block); end

    # get a stub matching params or nil
    # @param request_params [Hash<Symbol, >] request params to match against, omitted params match all
    # @return [Hash<Symbol, >] response params to return from matched request or block to call with params
    #
    # pkg:gem/excon#lib/excon.rb:186
    def stub_for(request_params = T.unsafe(nil)); end

    # get a list of defined stubs
    #
    # pkg:gem/excon#lib/excon.rb:234
    def stubs; end

    # pkg:gem/excon#lib/excon.rb:254
    def trace(url, params = T.unsafe(nil), &block); end

    # remove first/oldest stub matching request_params or nil if none match
    # @param request_params [Hash<Symbol, >] request params to match against, omitted params match all
    # @return [Hash<Symbol, >] response params from deleted stub
    #
    # pkg:gem/excon#lib/excon.rb:246
    def unstub(request_params = T.unsafe(nil)); end
  end
end

# avoid overwrite if somebody has redefined
#
# pkg:gem/excon#lib/excon/constants.rb:10
Excon::CHUNK_SIZE = T.let(T.unsafe(nil), Integer)

# pkg:gem/excon#lib/excon/constants.rb:3
Excon::CR_NL = T.let(T.unsafe(nil), String)

# pkg:gem/excon#lib/excon/connection.rb:4
class Excon::Connection
  include ::Excon::Utils

  # Initializes a new Connection instance
  # @param [Hash<Symbol, >] params One or more optional params
  # @option params [String] :body Default text to be sent over a socket. Only used if :body absent in Connection#request params
  # @option params [Hash<Symbol, String>] :headers The default headers to supply in a request. Only used if params[:headers] is not supplied to Connection#request
  # @option params [String] :host The destination host's reachable DNS name or IP, in the form of a String. IPv6 addresses must be wrapped (e.g. [::1]).  See URI#host.
  # @option params [String] :hostname Same as host, but usable for socket connections. IPv6 addresses must not be wrapped (e.g. ::1).  See URI#hostname.
  # @option params [String] :path Default path; appears after 'scheme://host:port/'. Only used if params[:path] is not supplied to Connection#request
  # @option params [Fixnum] :port The port on which to connect, to the destination host
  # @option params [Hash]   :query Default query; appended to the 'scheme://host:port/path/' in the form of '?key=value'. Will only be used if params[:query] is not supplied to Connection#request
  # @option params [String] :scheme The protocol; 'https' causes OpenSSL to be used
  # @option params [String] :socket The path to the unix socket (required for 'unix://' connections)
  # @option params [String] :ciphers Only use the specified SSL/TLS cipher suites; use OpenSSL cipher spec format e.g. 'HIGH:!aNULL:!3DES' or 'AES256-SHA:DES-CBC3-SHA'
  # @option params [String] :proxy Proxy server; e.g. 'http://myproxy.com:8888'
  # @option params [Fixnum] :retry_limit Set how many times we'll retry a failed request.  (Default 4)
  # @option params [Fixnum] :retry_interval Set how long to wait between retries. (Default 0)
  # @option params [Class] :instrumentor Responds to #instrument as in ActiveSupport::Notifications
  # @option params [String] :instrumentor_name Name prefix for #instrument events.  Defaults to 'excon'
  # @option params [Resolv, nil] :resolv_resolver A ready to use +Resolv+ resolver instance.
  # @option params [Class] :resolver_factory Const of the resolver factory.  Defaults to 'Excon::ResolverFactory'
  #
  # pkg:gem/excon#lib/excon/connection.rb:65
  def initialize(params = T.unsafe(nil)); end

  # Sends the supplied requests to the destination host using pipelining in
  # batches of @limit [Numeric] requests. This is your soft file descriptor
  # limit by default, typically 256.
  # @param pipeline_params [Array<Hash>] An array of one or more optional params, override defaults set in Connection.new, see #request for details
  #
  # pkg:gem/excon#lib/excon/connection.rb:359
  def batch_requests(pipeline_params, limit = T.unsafe(nil)); end

  # pkg:gem/excon#lib/excon/connection.rb:379
  def connect(params = T.unsafe(nil), &block); end

  # pkg:gem/excon#lib/excon/connection.rb:9
  def connection; end

  # pkg:gem/excon#lib/excon/connection.rb:13
  def connection=(new_params); end

  # pkg:gem/excon#lib/excon/connection.rb:7
  def data; end

  # pkg:gem/excon#lib/excon/connection.rb:379
  def delete(params = T.unsafe(nil), &block); end

  # pkg:gem/excon#lib/excon/connection.rb:110
  def error_call(datum); end

  # pkg:gem/excon#lib/excon/connection.rb:379
  def get(params = T.unsafe(nil), &block); end

  # pkg:gem/excon#lib/excon/connection.rb:379
  def head(params = T.unsafe(nil), &block); end

  # pkg:gem/excon#lib/excon/connection.rb:396
  def inspect; end

  # pkg:gem/excon#lib/excon/connection.rb:36
  def logger; end

  # pkg:gem/excon#lib/excon/connection.rb:41
  def logger=(logger); end

  # pkg:gem/excon#lib/excon/connection.rb:379
  def options(params = T.unsafe(nil), &block); end

  # pkg:gem/excon#lib/excon/connection.rb:18
  def params; end

  # pkg:gem/excon#lib/excon/connection.rb:22
  def params=(new_params); end

  # pkg:gem/excon#lib/excon/connection.rb:379
  def patch(params = T.unsafe(nil), &block); end

  # pkg:gem/excon#lib/excon/connection.rb:379
  def post(params = T.unsafe(nil), &block); end

  # pkg:gem/excon#lib/excon/connection.rb:27
  def proxy; end

  # pkg:gem/excon#lib/excon/connection.rb:31
  def proxy=(new_proxy); end

  # pkg:gem/excon#lib/excon/connection.rb:379
  def put(params = T.unsafe(nil), &block); end

  # Sends the supplied request to the destination host.
  # @yield [chunk] @see Response#self.parse
  # @param [Hash<Symbol, >] params One or more optional params, override defaults set in Connection.new
  # @option params [String] :body text to be sent over a socket
  # @option params [Hash<Symbol, String>] :headers The default headers to supply in a request
  # @option params [String] :path appears after 'scheme://host:port/'
  # @option params [Hash]   :query appended to the 'scheme://host:port/path/' in the form of '?key=value'
  #
  # pkg:gem/excon#lib/excon/connection.rb:231
  def request(params = T.unsafe(nil), &block); end

  # pkg:gem/excon#lib/excon/connection.rb:116
  def request_call(datum); end

  # Sends the supplied requests to the destination host using pipelining.
  # @param pipeline_params [Array<Hash>] An array of one or more optional params, override defaults set in Connection.new, see #request for details
  #
  # pkg:gem/excon#lib/excon/connection.rb:332
  def requests(pipeline_params); end

  # pkg:gem/excon#lib/excon/connection.rb:370
  def reset; end

  # pkg:gem/excon#lib/excon/connection.rb:210
  def response_call(datum); end

  # pkg:gem/excon#lib/excon/connection.rb:391
  def retry_limit; end

  # pkg:gem/excon#lib/excon/connection.rb:386
  def retry_limit=(new_retry_limit); end

  # pkg:gem/excon#lib/excon/connection.rb:379
  def trace(params = T.unsafe(nil), &block); end

  # pkg:gem/excon#lib/excon/connection.rb:410
  def valid_request_keys(middlewares); end

  private

  # pkg:gem/excon#lib/excon/connection.rb:416
  def detect_content_length(body); end

  # pkg:gem/excon#lib/excon/connection.rb:543
  def proxy_from_env; end

  # pkg:gem/excon#lib/excon/connection.rb:530
  def proxy_match_host_port(host, port); end

  # pkg:gem/excon#lib/excon/connection.rb:522
  def raise_socket_error(error); end

  # pkg:gem/excon#lib/excon/connection.rb:473
  def response(datum = T.unsafe(nil)); end

  # pkg:gem/excon#lib/excon/connection.rb:571
  def setup_proxy; end

  # pkg:gem/excon#lib/excon/connection.rb:484
  def socket(datum = T.unsafe(nil)); end

  # pkg:gem/excon#lib/excon/connection.rb:502
  def sockets; end

  # pkg:gem/excon#lib/excon/connection.rb:428
  def valid_middleware_keys(middlewares); end

  # pkg:gem/excon#lib/excon/connection.rb:441
  def validate_params(validation, params, middlewares); end
end

# pkg:gem/excon#lib/excon/constants.rb:189
Excon::DEFAULTS = T.let(T.unsafe(nil), Hash)

# pkg:gem/excon#lib/excon/constants.rb:5
Excon::DEFAULT_CA_FILE = T.let(T.unsafe(nil), String)

# pkg:gem/excon#lib/excon/constants.rb:7
Excon::DEFAULT_CHUNK_SIZE = T.let(T.unsafe(nil), Integer)

# pkg:gem/excon#lib/excon/constants.rb:12
Excon::DEFAULT_REDIRECT_LIMIT = T.let(T.unsafe(nil), Integer)

# pkg:gem/excon#lib/excon/constants.rb:16
Excon::DEFAULT_RETRY_ERRORS = T.let(T.unsafe(nil), Array)

# pkg:gem/excon#lib/excon/constants.rb:14
Excon::DEFAULT_RETRY_LIMIT = T.let(T.unsafe(nil), Integer)

# pkg:gem/excon#lib/excon/constants.rb:120
Excon::DEPRECATED_VALID_REQUEST_KEYS = T.let(T.unsafe(nil), Hash)

# Excon exception classes
#
# pkg:gem/excon#lib/excon/error.rb:4
class Excon::Error < ::StandardError
  class << self
    # Messages for nicer exceptions, from rfc2616
    #
    # pkg:gem/excon#lib/excon/error.rb:174
    def status_error(request, response); end

    # 504
    #
    # pkg:gem/excon#lib/excon/error.rb:127
    def status_errors; end
  end
end

# 201
#
# pkg:gem/excon#lib/excon/error.rb:89
class Excon::Error::Accepted < ::Excon::Error::Success; end

# 501
#
# pkg:gem/excon#lib/excon/error.rb:123
class Excon::Error::BadGateway < ::Excon::Error::Server; end

# 307
#
# pkg:gem/excon#lib/excon/error.rb:101
class Excon::Error::BadRequest < ::Excon::Error::Client; end

# Certificate related errors
#
# pkg:gem/excon#lib/excon/error.rb:27
class Excon::Error::Certificate < ::Excon::Error::Socket
  # pkg:gem/excon#lib/excon/error.rb:28
  def initialize(socket_error = T.unsafe(nil)); end
end

# pkg:gem/excon#lib/excon/error.rb:82
class Excon::Error::Client < ::Excon::Error::HTTPStatus; end

# 408
#
# pkg:gem/excon#lib/excon/error.rb:110
class Excon::Error::Conflict < ::Excon::Error::Client; end

# pkg:gem/excon#lib/excon/error.rb:85
class Excon::Error::Continue < ::Excon::Error::Informational; end

# 200
#
# pkg:gem/excon#lib/excon/error.rb:88
class Excon::Error::Created < ::Excon::Error::Success; end

# 416
#
# pkg:gem/excon#lib/excon/error.rb:118
class Excon::Error::ExpectationFailed < ::Excon::Error::Client; end

# 402
#
# pkg:gem/excon#lib/excon/error.rb:104
class Excon::Error::Forbidden < ::Excon::Error::Client; end

# 301
#
# pkg:gem/excon#lib/excon/error.rb:96
class Excon::Error::Found < ::Excon::Error::Redirection; end

# 503
#
# pkg:gem/excon#lib/excon/error.rb:125
class Excon::Error::GatewayTimeout < ::Excon::Error::Server; end

# 409
#
# pkg:gem/excon#lib/excon/error.rb:111
class Excon::Error::Gone < ::Excon::Error::Client; end

# Base class for HTTP Error classes
#
# pkg:gem/excon#lib/excon/error.rb:68
class Excon::Error::HTTPStatus < ::Excon::Error
  # pkg:gem/excon#lib/excon/error.rb:71
  def initialize(msg, request = T.unsafe(nil), response = T.unsafe(nil)); end

  # pkg:gem/excon#lib/excon/error.rb:69
  def request; end

  # pkg:gem/excon#lib/excon/error.rb:69
  def response; end
end

# HTTP Error classes
#
# pkg:gem/excon#lib/excon/error.rb:79
class Excon::Error::Informational < ::Excon::Error::HTTPStatus; end

# 429
#
# pkg:gem/excon#lib/excon/error.rb:121
class Excon::Error::InternalServerError < ::Excon::Error::Server; end

# pkg:gem/excon#lib/excon/error.rb:49
class Excon::Error::InvalidHeaderKey < ::Excon::Error; end

# pkg:gem/excon#lib/excon/error.rb:50
class Excon::Error::InvalidHeaderValue < ::Excon::Error; end

# pkg:gem/excon#lib/excon/error.rb:8
class Excon::Error::InvalidStub < ::Excon::Error; end

# 410
#
# pkg:gem/excon#lib/excon/error.rb:112
class Excon::Error::LengthRequired < ::Excon::Error::Client; end

# 404
#
# pkg:gem/excon#lib/excon/error.rb:106
class Excon::Error::MethodNotAllowed < ::Excon::Error::Client; end

# 300
#
# pkg:gem/excon#lib/excon/error.rb:95
class Excon::Error::MovedPermanently < ::Excon::Error::Redirection; end

# 206
#
# pkg:gem/excon#lib/excon/error.rb:94
class Excon::Error::MultipleChoices < ::Excon::Error::Redirection; end

# 203
#
# pkg:gem/excon#lib/excon/error.rb:91
class Excon::Error::NoContent < ::Excon::Error::Success; end

# 202
#
# pkg:gem/excon#lib/excon/error.rb:90
class Excon::Error::NonAuthoritativeInformation < ::Excon::Error::Success; end

# 405
#
# pkg:gem/excon#lib/excon/error.rb:107
class Excon::Error::NotAcceptable < ::Excon::Error::Client; end

# 403
#
# pkg:gem/excon#lib/excon/error.rb:105
class Excon::Error::NotFound < ::Excon::Error::Client; end

# 500
#
# pkg:gem/excon#lib/excon/error.rb:122
class Excon::Error::NotImplemented < ::Excon::Error::Server; end

# 303
#
# pkg:gem/excon#lib/excon/error.rb:98
class Excon::Error::NotModified < ::Excon::Error::Redirection; end

# 101
#
# pkg:gem/excon#lib/excon/error.rb:87
class Excon::Error::OK < ::Excon::Error::Success; end

# 205
#
# pkg:gem/excon#lib/excon/error.rb:93
class Excon::Error::PartialContent < ::Excon::Error::Success; end

# 401
#
# pkg:gem/excon#lib/excon/error.rb:103
class Excon::Error::PaymentRequired < ::Excon::Error::Client; end

# 411
#
# pkg:gem/excon#lib/excon/error.rb:113
class Excon::Error::PreconditionFailed < ::Excon::Error::Client; end

# 406
#
# pkg:gem/excon#lib/excon/error.rb:108
class Excon::Error::ProxyAuthenticationRequired < ::Excon::Error::Client; end

# pkg:gem/excon#lib/excon/error.rb:54
class Excon::Error::ProxyConnectionError < ::Excon::Error
  # pkg:gem/excon#lib/excon/error.rb:57
  def initialize(msg, request = T.unsafe(nil), response = T.unsafe(nil)); end

  # pkg:gem/excon#lib/excon/error.rb:55
  def request; end

  # pkg:gem/excon#lib/excon/error.rb:55
  def response; end
end

# pkg:gem/excon#lib/excon/error.rb:64
class Excon::Error::ProxyParse < ::Excon::Error; end

# pkg:gem/excon#lib/excon/error.rb:81
class Excon::Error::Redirection < ::Excon::Error::HTTPStatus; end

# 412
#
# pkg:gem/excon#lib/excon/error.rb:114
class Excon::Error::RequestEntityTooLarge < ::Excon::Error::Client; end

# 407
#
# pkg:gem/excon#lib/excon/error.rb:109
class Excon::Error::RequestTimeout < ::Excon::Error::Client; end

# 413
#
# pkg:gem/excon#lib/excon/error.rb:115
class Excon::Error::RequestURITooLong < ::Excon::Error::Client; end

# 415
#
# pkg:gem/excon#lib/excon/error.rb:117
class Excon::Error::RequestedRangeNotSatisfiable < ::Excon::Error::Client; end

# 204
#
# pkg:gem/excon#lib/excon/error.rb:92
class Excon::Error::ResetContent < ::Excon::Error::Success; end

# pkg:gem/excon#lib/excon/error.rb:52
class Excon::Error::ResponseParse < ::Excon::Error; end

# 302
#
# pkg:gem/excon#lib/excon/error.rb:97
class Excon::Error::SeeOther < ::Excon::Error::Redirection; end

# pkg:gem/excon#lib/excon/error.rb:83
class Excon::Error::Server < ::Excon::Error::HTTPStatus; end

# 502
#
# pkg:gem/excon#lib/excon/error.rb:124
class Excon::Error::ServiceUnavailable < ::Excon::Error::Server; end

# Socket related errors
#
# pkg:gem/excon#lib/excon/error.rb:12
class Excon::Error::Socket < ::Excon::Error
  # pkg:gem/excon#lib/excon/error.rb:15
  def initialize(socket_error = T.unsafe(nil)); end

  # pkg:gem/excon#lib/excon/error.rb:13
  def socket_error; end
end

# pkg:gem/excon#lib/excon/error.rb:7
class Excon::Error::StubNotFound < ::Excon::Error; end

# pkg:gem/excon#lib/excon/error.rb:80
class Excon::Error::Success < ::Excon::Error::HTTPStatus; end

# 100
#
# pkg:gem/excon#lib/excon/error.rb:86
class Excon::Error::SwitchingProtocols < ::Excon::Error::Informational; end

# 305
#
# pkg:gem/excon#lib/excon/error.rb:100
class Excon::Error::TemporaryRedirect < ::Excon::Error::Redirection; end

# pkg:gem/excon#lib/excon/error.rb:51
class Excon::Error::Timeout < ::Excon::Error; end

# pkg:gem/excon#lib/excon/error.rb:65
class Excon::Error::TooManyRedirects < ::Excon::Error; end

# 422
#
# pkg:gem/excon#lib/excon/error.rb:120
class Excon::Error::TooManyRequests < ::Excon::Error::Client; end

# 400
#
# pkg:gem/excon#lib/excon/error.rb:102
class Excon::Error::Unauthorized < ::Excon::Error::Client; end

# 417
#
# pkg:gem/excon#lib/excon/error.rb:119
class Excon::Error::UnprocessableEntity < ::Excon::Error::Client; end

# 414
#
# pkg:gem/excon#lib/excon/error.rb:116
class Excon::Error::UnsupportedMediaType < ::Excon::Error::Client; end

# 304
#
# pkg:gem/excon#lib/excon/error.rb:99
class Excon::Error::UseProxy < ::Excon::Error::Redirection; end

# pkg:gem/excon#lib/excon/error.rb:9
class Excon::Error::Warning < ::Excon::Error; end

# Legacy
#
# pkg:gem/excon#lib/excon/error.rb:199
module Excon::Errors
  class << self
    # pkg:gem/excon#lib/excon/error.rb:225
    def status_error(request, response); end
  end
end

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::Accepted = Excon::Error::Accepted

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::BadGateway = Excon::Error::BadGateway

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::BadRequest = Excon::Error::BadRequest

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::CertificateError = Excon::Error::Certificate

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::ClientError = Excon::Error::Client

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::Conflict = Excon::Error::Conflict

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::Continue = Excon::Error::Continue

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::Created = Excon::Error::Created

# pkg:gem/excon#lib/excon/error.rb:200
Excon::Errors::Error = Excon::Error

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::ExpectationFailed = Excon::Error::ExpectationFailed

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::Forbidden = Excon::Error::Forbidden

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::Found = Excon::Error::Found

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::GatewayTimeout = Excon::Error::GatewayTimeout

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::Gone = Excon::Error::Gone

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::HTTPStatusError = Excon::Error::HTTPStatus

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::Informational = Excon::Error::Informational

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::InternalServerError = Excon::Error::InternalServerError

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::InvalidHeaderKey = Excon::Error::InvalidHeaderKey

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::InvalidHeaderValue = Excon::Error::InvalidHeaderValue

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::InvalidStub = Excon::Error::InvalidStub

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::LengthRequired = Excon::Error::LengthRequired

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::MethodNotAllowed = Excon::Error::MethodNotAllowed

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::MovedPermanently = Excon::Error::MovedPermanently

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::MultipleChoices = Excon::Error::MultipleChoices

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::NoContent = Excon::Error::NoContent

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::NonAuthoritativeInformation = Excon::Error::NonAuthoritativeInformation

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::NotAcceptable = Excon::Error::NotAcceptable

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::NotFound = Excon::Error::NotFound

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::NotImplemented = Excon::Error::NotImplemented

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::NotModified = Excon::Error::NotModified

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::OK = Excon::Error::OK

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::PartialContent = Excon::Error::PartialContent

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::PaymentRequired = Excon::Error::PaymentRequired

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::PreconditionFailed = Excon::Error::PreconditionFailed

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::ProxyAuthenticationRequired = Excon::Error::ProxyAuthenticationRequired

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::ProxyConnectionError = Excon::Error::ProxyConnectionError

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::ProxyParse = Excon::Error::ProxyParse

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::Redirection = Excon::Error::Redirection

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::RequestEntityTooLarge = Excon::Error::RequestEntityTooLarge

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::RequestTimeout = Excon::Error::RequestTimeout

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::RequestURITooLong = Excon::Error::RequestURITooLong

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::RequestedRangeNotSatisfiable = Excon::Error::RequestedRangeNotSatisfiable

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::ResetContent = Excon::Error::ResetContent

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::ResponseParse = Excon::Error::ResponseParse

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::SeeOther = Excon::Error::SeeOther

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::ServerError = Excon::Error::Server

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::ServiceUnavailable = Excon::Error::ServiceUnavailable

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::SocketError = Excon::Error::Socket

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::StubNotFound = Excon::Error::StubNotFound

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::Success = Excon::Error::Success

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::SwitchingProtocols = Excon::Error::SwitchingProtocols

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::TemporaryRedirect = Excon::Error::TemporaryRedirect

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::Timeout = Excon::Error::Timeout

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::TooManyRedirects = Excon::Error::TooManyRedirects

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::TooManyRequests = Excon::Error::TooManyRequests

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::Unauthorized = Excon::Error::Unauthorized

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::UnprocessableEntity = Excon::Error::UnprocessableEntity

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::UnsupportedMediaType = Excon::Error::UnsupportedMediaType

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::UseProxy = Excon::Error::UseProxy

# pkg:gem/excon#lib/excon/error.rb:222
Excon::Errors::Warning = Excon::Error::Warning

# pkg:gem/excon#lib/excon/constants.rb:24
Excon::FORCE_ENC = T.let(T.unsafe(nil), TrueClass)

# pkg:gem/excon#lib/excon/constants.rb:30
Excon::HTTPS = T.let(T.unsafe(nil), String)

# pkg:gem/excon#lib/excon/constants.rb:26
Excon::HTTP_1_1 = T.let(T.unsafe(nil), String)

# pkg:gem/excon#lib/excon/constants.rb:28
Excon::HTTP_VERBS = T.let(T.unsafe(nil), Array)

# pkg:gem/excon#lib/excon/headers.rb:3
class Excon::Headers < ::Hash
  # pkg:gem/excon#lib/excon/headers.rb:24
  def initialize; end

  # pkg:gem/excon#lib/excon/headers.rb:29
  def [](key); end

  # pkg:gem/excon#lib/excon/headers.rb:33
  def []=(key, value); end

  # pkg:gem/excon#lib/excon/headers.rb:40
  def assoc(obj); end

  # pkg:gem/excon#lib/excon/headers.rb:45
  def delete(key, &proc); end

  # pkg:gem/excon#lib/excon/headers.rb:50
  def fetch(key, default = T.unsafe(nil), &proc); end

  # pkg:gem/excon#lib/excon/headers.rb:58
  def has_key?(key); end

  # pkg:gem/excon#lib/excon/headers.rb:61
  def key?(key); end

  # pkg:gem/excon#lib/excon/headers.rb:62
  def member?(key); end

  # pkg:gem/excon#lib/excon/headers.rb:64
  def merge(other_hash); end

  # pkg:gem/excon#lib/excon/headers.rb:68
  def merge!(other_hash); end

  # pkg:gem/excon#lib/excon/headers.rb:10
  def raw_assoc(_arg0); end

  # pkg:gem/excon#lib/excon/headers.rb:12
  def raw_delete(_arg0); end

  # pkg:gem/excon#lib/excon/headers.rb:13
  def raw_fetch(*_arg0); end

  # pkg:gem/excon#lib/excon/headers.rb:14
  def raw_has_key?(_arg0); end

  # pkg:gem/excon#lib/excon/headers.rb:15
  def raw_include?(_arg0); end

  # pkg:gem/excon#lib/excon/headers.rb:16
  def raw_key?(_arg0); end

  # pkg:gem/excon#lib/excon/headers.rb:17
  def raw_member?(_arg0); end

  # pkg:gem/excon#lib/excon/headers.rb:18
  def raw_merge(*_arg0); end

  # pkg:gem/excon#lib/excon/headers.rb:19
  def raw_merge!(*_arg0); end

  # pkg:gem/excon#lib/excon/headers.rb:8
  def raw_reader(_arg0); end

  # pkg:gem/excon#lib/excon/headers.rb:20
  def raw_rehash; end

  # pkg:gem/excon#lib/excon/headers.rb:21
  def raw_store(_arg0, _arg1); end

  # pkg:gem/excon#lib/excon/headers.rb:22
  def raw_values_at(*_arg0); end

  # pkg:gem/excon#lib/excon/headers.rb:7
  def raw_writer(_arg0, _arg1); end

  # pkg:gem/excon#lib/excon/headers.rb:75
  def rehash; end

  # pkg:gem/excon#lib/excon/headers.rb:37
  def store(key, value); end

  # pkg:gem/excon#lib/excon/headers.rb:80
  def values_at(*keys); end
end

# pkg:gem/excon#lib/excon/headers.rb:5
Excon::Headers::SENTINEL = T.let(T.unsafe(nil), Hash)

# pkg:gem/excon#lib/excon/instrumentors/logging_instrumentor.rb:4
class Excon::LoggingInstrumentor
  class << self
    # pkg:gem/excon#lib/excon/instrumentors/logging_instrumentor.rb:6
    def instrument(name, params = T.unsafe(nil)); end
  end
end

# pkg:gem/excon#lib/excon/middlewares/base.rb:3
module Excon::Middleware; end

# pkg:gem/excon#lib/excon/middlewares/base.rb:4
class Excon::Middleware::Base
  # pkg:gem/excon#lib/excon/middlewares/base.rb:11
  def initialize(stack); end

  # pkg:gem/excon#lib/excon/middlewares/base.rb:15
  def error_call(datum); end

  # pkg:gem/excon#lib/excon/middlewares/base.rb:20
  def request_call(datum); end

  # pkg:gem/excon#lib/excon/middlewares/base.rb:25
  def response_call(datum); end

  class << self
    # Returns the list of parameters that this middleware uses that are valid
    # as arguments to `Connection#request` or `Connection#new`.
    #
    # pkg:gem/excon#lib/excon/middlewares/base.rb:7
    def valid_parameter_keys; end
  end
end

# pkg:gem/excon#lib/excon/middlewares/capture_cookies.rb:4
class Excon::Middleware::CaptureCookies < ::Excon::Middleware::Base
  # pkg:gem/excon#lib/excon/middlewares/capture_cookies.rb:6
  def extract_cookies_from_set_cookie(set_cookie); end

  # pkg:gem/excon#lib/excon/middlewares/capture_cookies.rb:10
  def get_header(datum, header); end

  # pkg:gem/excon#lib/excon/middlewares/capture_cookies.rb:17
  def response_call(datum); end
end

# pkg:gem/excon#lib/excon/middlewares/decompress.rb:5
class Excon::Middleware::Decompress < ::Excon::Middleware::Base
  # Zlib::MAX_WBITS * -1
  #
  # pkg:gem/excon#lib/excon/middlewares/decompress.rb:9
  def request_call(datum); end

  # pkg:gem/excon#lib/excon/middlewares/decompress.rb:17
  def response_call(datum); end
end

# Zlib::MAX_WBITS + 32
#
# pkg:gem/excon#lib/excon/middlewares/decompress.rb:7
Excon::Middleware::Decompress::INFLATE_RAW = T.let(T.unsafe(nil), Integer)

# pkg:gem/excon#lib/excon/middlewares/decompress.rb:6
Excon::Middleware::Decompress::INFLATE_ZLIB_OR_GZIP = T.let(T.unsafe(nil), Integer)

# pkg:gem/excon#lib/excon/middlewares/escape_path.rb:4
class Excon::Middleware::EscapePath < ::Excon::Middleware::Base
  # pkg:gem/excon#lib/excon/middlewares/escape_path.rb:5
  def request_call(datum); end
end

# pkg:gem/excon#lib/excon/middlewares/expects.rb:4
class Excon::Middleware::Expects < ::Excon::Middleware::Base
  # pkg:gem/excon#lib/excon/middlewares/expects.rb:11
  def response_call(datum); end

  class << self
    # pkg:gem/excon#lib/excon/middlewares/expects.rb:5
    def valid_parameter_keys; end
  end
end

# pkg:gem/excon#lib/excon/middlewares/idempotent.rb:6
class Excon::Middleware::Idempotent < ::Excon::Middleware::Base
  # pkg:gem/excon#lib/excon/middlewares/idempotent.rb:22
  def error_call(datum); end

  # pkg:gem/excon#lib/excon/middlewares/idempotent.rb:17
  def request_call(datum); end

  class << self
    # pkg:gem/excon#lib/excon/middlewares/idempotent.rb:7
    def valid_parameter_keys; end
  end
end

# pkg:gem/excon#lib/excon/middlewares/instrumentor.rb:4
class Excon::Middleware::Instrumentor < ::Excon::Middleware::Base
  # pkg:gem/excon#lib/excon/middlewares/instrumentor.rb:13
  def error_call(datum); end

  # pkg:gem/excon#lib/excon/middlewares/instrumentor.rb:23
  def request_call(datum); end

  # pkg:gem/excon#lib/excon/middlewares/instrumentor.rb:38
  def response_call(datum); end

  class << self
    # pkg:gem/excon#lib/excon/middlewares/instrumentor.rb:5
    def valid_parameter_keys; end
  end
end

# pkg:gem/excon#lib/excon/middlewares/mock.rb:4
class Excon::Middleware::Mock < ::Excon::Middleware::Base
  # pkg:gem/excon#lib/excon/middlewares/mock.rb:13
  def request_call(datum); end

  class << self
    # pkg:gem/excon#lib/excon/middlewares/mock.rb:5
    def valid_parameter_keys; end
  end
end

# pkg:gem/excon#lib/excon/middlewares/redirect_follower.rb:4
class Excon::Middleware::RedirectFollower < ::Excon::Middleware::Base
  # pkg:gem/excon#lib/excon/middlewares/redirect_follower.rb:18
  def get_header(datum, header); end

  # pkg:gem/excon#lib/excon/middlewares/redirect_follower.rb:12
  def request_call(datum); end

  # pkg:gem/excon#lib/excon/middlewares/redirect_follower.rb:25
  def response_call(datum); end

  class << self
    # pkg:gem/excon#lib/excon/middlewares/redirect_follower.rb:5
    def valid_parameter_keys; end
  end
end

# pkg:gem/excon#lib/excon/middlewares/response_parser.rb:4
class Excon::Middleware::ResponseParser < ::Excon::Middleware::Base
  # pkg:gem/excon#lib/excon/middlewares/response_parser.rb:5
  def response_call(datum); end
end

# pkg:gem/excon#lib/excon/constants.rb:32
Excon::NO_ENTITY = T.let(T.unsafe(nil), Array)

# pkg:gem/excon#lib/excon/pretty_printer.rb:3
class Excon::PrettyPrinter
  class << self
    # pkg:gem/excon#lib/excon/pretty_printer.rb:4
    def pp(io, datum, indent = T.unsafe(nil)); end
  end
end

# pkg:gem/excon#lib/excon/constants.rb:34
Excon::REDACTED = T.let(T.unsafe(nil), String)

# This factory produces new +resolv+ gem resolver instances. Users who wants
# to configure a custom resolver (varying settings for varying resolvers) can
# provide a custom resolver factory class and configure it globally on the
# Excon defaults:
#
#   Excon.defaults[:resolver_factory] = MyCustomResolverFactory
#
# Then you just need to provide a static method called +.create_resolver+
# which returns a new +Resolv+ instance. This allows the customization.
#
# pkg:gem/excon#lib/excon/resolver_factory.rb:12
class Excon::ResolverFactory
  class << self
    # @return [Resolv] the new resolver instance
    #
    # pkg:gem/excon#lib/excon/resolver_factory.rb:14
    def create_resolver; end
  end
end

# pkg:gem/excon#lib/excon/response.rb:3
class Excon::Response
  # pkg:gem/excon#lib/excon/response.rb:213
  def initialize(params = T.unsafe(nil)); end

  # pkg:gem/excon#lib/excon/response.rb:227
  def [](key); end

  # pkg:gem/excon#lib/excon/response.rb:11
  def body; end

  # backwards compatability reader/writers
  #
  # pkg:gem/excon#lib/excon/response.rb:8
  def body=(new_body); end

  # pkg:gem/excon#lib/excon/response.rb:5
  def data; end

  # pkg:gem/excon#lib/excon/response.rb:5
  def data=(_arg0); end

  # Retrieve a specific header value. Header names are treated case-insensitively.
  # @param [String] name Header name
  #
  # pkg:gem/excon#lib/excon/response.rb:242
  def get_header(name); end

  # pkg:gem/excon#lib/excon/response.rb:17
  def headers; end

  # pkg:gem/excon#lib/excon/response.rb:14
  def headers=(new_headers); end

  # pkg:gem/excon#lib/excon/response.rb:20
  def host; end

  # pkg:gem/excon#lib/excon/response.rb:32
  def http_method; end

  # pkg:gem/excon#lib/excon/response.rb:26
  def local_address; end

  # pkg:gem/excon#lib/excon/response.rb:29
  def local_port; end

  # pkg:gem/excon#lib/excon/response.rb:231
  def params; end

  # pkg:gem/excon#lib/excon/response.rb:35
  def path; end

  # pkg:gem/excon#lib/excon/response.rb:41
  def port; end

  # pkg:gem/excon#lib/excon/response.rb:236
  def pp; end

  # pkg:gem/excon#lib/excon/response.rb:38
  def query; end

  # pkg:gem/excon#lib/excon/response.rb:47
  def reason_phrase; end

  # pkg:gem/excon#lib/excon/response.rb:44
  def reason_phrase=(new_reason_phrase); end

  # pkg:gem/excon#lib/excon/response.rb:53
  def remote_ip; end

  # pkg:gem/excon#lib/excon/response.rb:50
  def remote_ip=(new_remote_ip); end

  # pkg:gem/excon#lib/excon/response.rb:23
  def scheme; end

  # pkg:gem/excon#lib/excon/response.rb:59
  def status; end

  # pkg:gem/excon#lib/excon/response.rb:56
  def status=(new_status); end

  # pkg:gem/excon#lib/excon/response.rb:62
  def status_line; end

  # pkg:gem/excon#lib/excon/response.rb:65
  def status_line=(new_status_line); end

  class << self
    # pkg:gem/excon#lib/excon/response.rb:69
    def parse(socket, datum); end

    # pkg:gem/excon#lib/excon/response.rb:193
    def parse_headers(socket, datum); end
  end
end

# SOCKS5 protocol implementation (RFC 1928, RFC 1929)
# Shared module for SOCKS5Socket and SOCKS5SSLSocket
#
# pkg:gem/excon#lib/excon/socks5.rb:6
module Excon::SOCKS5
  private

  # Parse SOCKS5 proxy string into components
  # @param proxy_string [String] Proxy specification in various formats
  # @return [Array<String, String, String, String>] host, port, user, pass
  #
  # pkg:gem/excon#lib/excon/socks5.rb:44
  def parse_socks5_proxy(proxy_string); end

  # Perform SOCKS5 authentication handshake
  #
  # pkg:gem/excon#lib/excon/socks5.rb:69
  def socks5_authenticate; end

  # Request connection to target through SOCKS5 proxy
  #
  # pkg:gem/excon#lib/excon/socks5.rb:122
  def socks5_connect(host, port); end

  # pkg:gem/excon#lib/excon/socks5.rb:150
  def socks5_read_bound_address(atyp); end

  # Read exact number of bytes with timeout support
  #
  # pkg:gem/excon#lib/excon/socks5.rb:165
  def socks5_read_exactly(nbytes); end

  # RFC 1929: Username/Password Authentication
  #
  # pkg:gem/excon#lib/excon/socks5.rb:102
  def socks5_username_password_auth; end
end

# Maximum hostname length per RFC 1928
#
# pkg:gem/excon#lib/excon/socks5.rb:37
Excon::SOCKS5::MAX_HOSTNAME_LENGTH = T.let(T.unsafe(nil), Integer)

# pkg:gem/excon#lib/excon/socks5.rb:20
Excon::SOCKS5::SOCKS5_ATYP_DOMAIN = T.let(T.unsafe(nil), Integer)

# Address types
#
# pkg:gem/excon#lib/excon/socks5.rb:19
Excon::SOCKS5::SOCKS5_ATYP_IPV4 = T.let(T.unsafe(nil), Integer)

# pkg:gem/excon#lib/excon/socks5.rb:21
Excon::SOCKS5::SOCKS5_ATYP_IPV6 = T.let(T.unsafe(nil), Integer)

# pkg:gem/excon#lib/excon/socks5.rb:12
Excon::SOCKS5::SOCKS5_AUTH_USERNAME_PASSWORD = T.let(T.unsafe(nil), Integer)

# Commands
#
# pkg:gem/excon#lib/excon/socks5.rb:16
Excon::SOCKS5::SOCKS5_CMD_CONNECT = T.let(T.unsafe(nil), Integer)

# pkg:gem/excon#lib/excon/socks5.rb:25
Excon::SOCKS5::SOCKS5_ERRORS = T.let(T.unsafe(nil), Hash)

# pkg:gem/excon#lib/excon/socks5.rb:13
Excon::SOCKS5::SOCKS5_NO_ACCEPTABLE_AUTH = T.let(T.unsafe(nil), Integer)

# Authentication methods
#
# pkg:gem/excon#lib/excon/socks5.rb:11
Excon::SOCKS5::SOCKS5_NO_AUTH = T.let(T.unsafe(nil), Integer)

# pkg:gem/excon#lib/excon/socks5.rb:8
Excon::SOCKS5::SOCKS5_RESERVED = T.let(T.unsafe(nil), Integer)

# Reply codes
#
# pkg:gem/excon#lib/excon/socks5.rb:24
Excon::SOCKS5::SOCKS5_SUCCESS = T.let(T.unsafe(nil), Integer)

# pkg:gem/excon#lib/excon/socks5.rb:7
Excon::SOCKS5::SOCKS5_VERSION = T.let(T.unsafe(nil), Integer)

# pkg:gem/excon#lib/excon/socks5_ssl_socket.rb:4
class Excon::SOCKS5SSLSocket < ::Excon::SSLSocket
  include ::Excon::SOCKS5

  # pkg:gem/excon#lib/excon/socks5_ssl_socket.rb:7
  def initialize(data = T.unsafe(nil)); end

  private

  # Proxy-swap pattern (same as SOCKS5Socket#connect).
  #
  # Call chain:
  #   SOCKS5SSLSocket#initialize -> super (SSLSocket#initialize)
  #     -> super (Socket#initialize) -> connect
  #       -> SOCKS5SSLSocket#connect (this method)
  #         -> super -> SSLSocket#connect -> Socket#connect (TCP to proxy)
  #       -> SOCKS5 handshake on raw TCP socket
  #     <- returns to SSLSocket#initialize
  #     -> @data[:proxy] is nil, so HTTP CONNECT is skipped (line 111)
  #     -> SSL wrapping on the SOCKS5-tunneled socket
  #
  # pkg:gem/excon#lib/excon/socks5_ssl_socket.rb:26
  def connect; end
end

# pkg:gem/excon#lib/excon/socks5_socket.rb:4
class Excon::SOCKS5Socket < ::Excon::Socket
  include ::Excon::SOCKS5

  # pkg:gem/excon#lib/excon/socks5_socket.rb:7
  def initialize(data = T.unsafe(nil)); end

  private

  # Proxy-swap pattern: temporarily set @data[:proxy] to the SOCKS5 proxy
  # so that Socket#connect routes the TCP connection there (inheriting DNS
  # resolution, nonblock, retry, keepalive, reuseaddr, remote_ip tracking).
  # After TCP is up, clear :proxy and run the SOCKS5 handshake.
  #
  # pkg:gem/excon#lib/excon/socks5_socket.rb:19
  def connect; end
end

# pkg:gem/excon#lib/excon/ssl_socket.rb:3
class Excon::SSLSocket < ::Excon::Socket
  # pkg:gem/excon#lib/excon/ssl_socket.rb:8
  def initialize(data = T.unsafe(nil)); end

  private

  # pkg:gem/excon#lib/excon/ssl_socket.rb:172
  def client_cert_data; end

  # pkg:gem/excon#lib/excon/ssl_socket.rb:183
  def client_chain_data; end

  # pkg:gem/excon#lib/excon/ssl_socket.rb:197
  def client_key_data; end

  # pkg:gem/excon#lib/excon/ssl_socket.rb:208
  def client_key_pass; end

  # pkg:gem/excon#lib/excon/ssl_socket.rb:191
  def connect; end
end

# pkg:gem/excon#lib/excon/ssl_socket.rb:4
Excon::SSLSocket::HAVE_NONBLOCK = T.let(T.unsafe(nil), TrueClass)

# pkg:gem/excon#lib/excon/socket.rb:5
class Excon::Socket
  include ::Excon::Utils
  extend ::Forwardable

  # pkg:gem/excon#lib/excon/socket.rb:51
  def initialize(data = T.unsafe(nil)); end

  # pkg:gem/excon#lib/excon/socket.rb:48
  def close(*args, **_arg1, &block); end

  # pkg:gem/excon#lib/excon/socket.rb:10
  def data; end

  # pkg:gem/excon#lib/excon/socket.rb:10
  def data=(_arg0); end

  # pkg:gem/excon#lib/excon/socket.rb:112
  def local_address; end

  # pkg:gem/excon#lib/excon/socket.rb:116
  def local_port; end

  # pkg:gem/excon#lib/excon/socket.rb:36
  def params; end

  # pkg:gem/excon#lib/excon/socket.rb:41
  def params=(new_params); end

  # pkg:gem/excon#lib/excon/socket.rb:63
  def read(max_length = T.unsafe(nil)); end

  # pkg:gem/excon#lib/excon/socket.rb:73
  def readline; end

  # pkg:gem/excon#lib/excon/socket.rb:46
  def remote_ip; end

  # pkg:gem/excon#lib/excon/socket.rb:104
  def write(data); end

  private

  # pkg:gem/excon#lib/excon/socket.rb:122
  def connect; end

  # Consume any bytes remaining in the read buffer before making a system call.
  #
  # pkg:gem/excon#lib/excon/socket.rb:212
  def consume_read_buffer; end

  # pkg:gem/excon#lib/excon/socket.rb:296
  def read_block(max_length); end

  # pkg:gem/excon#lib/excon/socket.rb:227
  def read_nonblock(max_length); end

  # pkg:gem/excon#lib/excon/socket.rb:292
  def readable_bytes; end

  # Returns the remaining time in seconds until we reach the deadline for the request timeout.
  # Raises an exception if we have exceeded the request timeout's deadline.
  #
  # pkg:gem/excon#lib/excon/socket.rb:383
  def request_time_remaining; end

  # Rewind the read buffer to just after the given index.
  # The offset is moved back to the start of the current chunk and then forward until just after the index.
  #
  # pkg:gem/excon#lib/excon/socket.rb:222
  def rewind_read_buffer(chunk, idx); end

  # pkg:gem/excon#lib/excon/socket.rb:349
  def select_with_timeout(socket, type); end

  # pkg:gem/excon#lib/excon/socket.rb:375
  def unpacked_sockaddr; end

  # pkg:gem/excon#lib/excon/socket.rb:341
  def write_block(data); end

  # pkg:gem/excon#lib/excon/socket.rb:308
  def write_nonblock(data); end
end

# read/write drawn from https://github.com/ruby-amqp/bunny/commit/75d9dd79551b31a5dd3d1254c537bad471f108cf
#
# pkg:gem/excon#lib/excon/socket.rb:13
Excon::Socket::CONNECT_RETRY_EXCEPTION_CLASSES = T.let(T.unsafe(nil), Array)

# Maps a socket operation to a timeout property.
#
# pkg:gem/excon#lib/excon/socket.rb:29
Excon::Socket::OPERATION_TO_TIMEOUT = T.let(T.unsafe(nil), Hash)

# pkg:gem/excon#lib/excon/socket.rb:18
Excon::Socket::READ_RETRY_EXCEPTION_CLASSES = T.let(T.unsafe(nil), Array)

# pkg:gem/excon#lib/excon/socket.rb:23
Excon::Socket::WRITE_RETRY_EXCEPTION_CLASSES = T.let(T.unsafe(nil), Array)

# pkg:gem/excon#lib/excon/instrumentors/standard_instrumentor.rb:3
class Excon::StandardInstrumentor
  class << self
    # pkg:gem/excon#lib/excon/instrumentors/standard_instrumentor.rb:4
    def instrument(name, params = T.unsafe(nil)); end
  end
end

# pkg:gem/excon#lib/excon/constants.rb:36
Excon::UNIX = T.let(T.unsafe(nil), String)

# pkg:gem/excon#lib/excon/constants.rb:38
Excon::USER_AGENT = T.let(T.unsafe(nil), String)

# pkg:gem/excon#lib/excon/unix_socket.rb:3
class Excon::UnixSocket < ::Excon::Socket
  private

  # pkg:gem/excon#lib/excon/unix_socket.rb:7
  def connect; end
end

# pkg:gem/excon#lib/excon/utils.rb:4
module Excon::Utils
  private

  # pkg:gem/excon#lib/excon/utils.rb:14
  def binary_encode(string); end

  # pkg:gem/excon#lib/excon/utils.rb:26
  def connection_uri(datum = T.unsafe(nil)); end

  # pkg:gem/excon#lib/excon/utils.rb:66
  def default_port?(datum); end

  # Escapes HTTP reserved and unwise characters in +str+
  #
  # pkg:gem/excon#lib/excon/utils.rb:105
  def escape_uri(str); end

  # Performs validation on the passed header hash and returns a string representation of the headers
  #
  # pkg:gem/excon#lib/excon/utils.rb:127
  def headers_hash_to_s(headers); end

  # pkg:gem/excon#lib/excon/utils.rb:58
  def port_string(datum); end

  # pkg:gem/excon#lib/excon/utils.rb:72
  def query_string(datum); end

  # Redact sensitive info from provided data
  #
  # pkg:gem/excon#lib/excon/utils.rb:37
  def redact(datum); end

  # pkg:gem/excon#lib/excon/utils.rb:54
  def request_uri(datum); end

  # Splits a header value +str+ according to HTTP specification.
  #
  # pkg:gem/excon#lib/excon/utils.rb:95
  def split_header_value(str); end

  # Unescape form encoded values in +str+
  #
  # pkg:gem/excon#lib/excon/utils.rb:119
  def unescape_form(str); end

  # Unescapes HTTP reserved and unwise characters in +str+
  #
  # pkg:gem/excon#lib/excon/utils.rb:112
  def unescape_uri(str); end

  class << self
    # pkg:gem/excon#lib/excon/utils.rb:14
    def binary_encode(string); end

    # pkg:gem/excon#lib/excon/utils.rb:26
    def connection_uri(datum = T.unsafe(nil)); end

    # pkg:gem/excon#lib/excon/utils.rb:66
    def default_port?(datum); end

    # Escapes HTTP reserved and unwise characters in +str+
    #
    # pkg:gem/excon#lib/excon/utils.rb:105
    def escape_uri(str); end

    # Performs validation on the passed header hash and returns a string representation of the headers
    #
    # pkg:gem/excon#lib/excon/utils.rb:127
    def headers_hash_to_s(headers); end

    # pkg:gem/excon#lib/excon/utils.rb:58
    def port_string(datum); end

    # pkg:gem/excon#lib/excon/utils.rb:72
    def query_string(datum); end

    # Redact sensitive info from provided data
    #
    # pkg:gem/excon#lib/excon/utils.rb:37
    def redact(datum); end

    # pkg:gem/excon#lib/excon/utils.rb:54
    def request_uri(datum); end

    # Splits a header value +str+ according to HTTP specification.
    #
    # pkg:gem/excon#lib/excon/utils.rb:95
    def split_header_value(str); end

    # Unescape form encoded values in +str+
    #
    # pkg:gem/excon#lib/excon/utils.rb:119
    def unescape_form(str); end

    # Unescapes HTTP reserved and unwise characters in +str+
    #
    # pkg:gem/excon#lib/excon/utils.rb:112
    def unescape_uri(str); end
  end
end

# pkg:gem/excon#lib/excon/utils.rb:7
Excon::Utils::CONTROL = T.let(T.unsafe(nil), String)

# pkg:gem/excon#lib/excon/utils.rb:8
Excon::Utils::DELIMS = T.let(T.unsafe(nil), String)

# pkg:gem/excon#lib/excon/utils.rb:12
Excon::Utils::ESCAPED = T.let(T.unsafe(nil), Regexp)

# pkg:gem/excon#lib/excon/utils.rb:10
Excon::Utils::NONASCII = T.let(T.unsafe(nil), String)

# pkg:gem/excon#lib/excon/utils.rb:11
Excon::Utils::UNESCAPED = T.let(T.unsafe(nil), Regexp)

# pkg:gem/excon#lib/excon/utils.rb:9
Excon::Utils::UNWISE = T.let(T.unsafe(nil), String)

# FIXME: should be frozen, but with a way to change them, similar to defaults
#
# pkg:gem/excon#lib/excon/constants.rb:73
Excon::VALID_CONNECTION_KEYS = T.let(T.unsafe(nil), Array)

# FIXME: should be frozen, but with a way to change them, similar to defaults
#
# pkg:gem/excon#lib/excon/constants.rb:43
Excon::VALID_REQUEST_KEYS = T.let(T.unsafe(nil), Array)

# pkg:gem/excon#lib/excon/version.rb:4
Excon::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/excon#lib/excon/constants.rb:40
Excon::VERSIONS = T.let(T.unsafe(nil), String)
