# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby2_keywords` gem.
# Please instead update this file by running `bin/tapioca gem ruby2_keywords`.


# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca#manually-requiring-parts-of-a-gem
