load("@rules_go//go:def.bzl", "go_library", "go_binary")
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "my_lib",
    srcs = ["lib.cc"],
    deps = [
        "@abseil-cpp//absl/strings",
    ],
)