#!/usr/bin/env bash

set -e

bundle install
bundle exec turbo_tests2 --verbose

# Should we only run these on one of the CI_NODE_INDEX's?
cd /opt/bun && npm run lint && cd -
cd /opt/bun && npm test && cd -
