shared: &shared
  - .dockerignore
  - Dockerfile.updater-core
  - 'common/**'
  - 'updater/Gemfil*'
  - 'omnibus/**'
  - '.github/workflows/ci.yml'
rakefile_tests:
  - 'rakelib/**'
  - 'Rakefile'
  - 'script/test-rakefile'
dry_run:
  - *shared
  - 'bin/dry-run.rb'
  - 'bin/spec/**'
bun:
  - *shared
  - 'bun/**'
bundler:
  - *shared
  - 'bundler/**'
cargo:
  - *shared
  - 'cargo/**'
common:
  - *shared
  - '**/**'
composer:
  - *shared
  - 'composer/**'
conda:
  - *shared
  - 'conda/**'
devcontainers:
  - *shared
  - 'devcontainers/**'
docker:
  - *shared
  - 'docker/**'
docker_compose:
  - *shared
  - 'docker_compose/**'
dotnet_sdk:
  - *shared
  - 'dotnet_sdk/**'
elm:
  - *shared
  - 'elm/**'
git_submodules:
  - *shared
  - 'git_submodules/**'
github_actions:
  - *shared
  - 'github_actions/**'
go_modules:
  - *shared
  - 'go_modules/**'
gradle:
  - *shared
  - 'maven/**'
  - 'gradle/**'
hex:
  - *shared
  - 'hex/**'
julia:
  - *shared
  - 'julia/**'
maven:
  - *shared
  - 'maven/**'
npm_and_yarn:
  - *shared
  - 'npm_and_yarn/**'
nuget:
  - *shared
  - 'nuget/**'
pub:
  - *shared
  - 'pub/**'
python:
  - *shared
  - 'python/**'
rust_toolchain:
  - *shared
  - 'rust_toolchain/**'
swift:
  - *shared
  - 'swift/**'
terraform:
  - *shared
  - 'terraform/**'
uv:
  - *shared
  - 'uv/**'
helm:
  - *shared
  - 'helm/**'
vcpkg:
  - *shared
  - 'vcpkg/**'
