
"L: test:ecosystem":
    - '(test[ecosystem)'
"L: ruby:bundler":
    - '(ruby|bundler)'

"L: rust:cargo":
    - '(rust|cargo)'

"L: rust:rust-toolchain":
    - '(rust[-_]toolchain)'

"L: php:composer":
    - '(php|composer)'

"L: cpp:vcpkg":
    - '(vcpkg)'

"L: devcontainers":
    - '(devcontainers)'

"L: docker":
    - '(docker|kubernetes)'

"L: docker:compose":
    - '(docker_compose)'

"L: elm":
    - '(elm)'

"L: git:submodules":
    - '(submodules)'

"L: github:actions":
    - '(actions)'

"L: go:modules":
    - '(golang|gomod)'

"L: javascript":
    - '(javascript|npm|pnpm|yarn|bun)'

"L: java:gradle":
    - '(gradle)'

"L: elixir:hex":
    - '(hex)'

"L: java:maven":
    - '(maven)'

"L: dotnet:nuget":
    - '(nuget)'

"L: dotnet:dotnet-sdk":
    - '(dotnet(?:[-_]sdk)?|\.NET)'

"L: dart:pub":
    - '(dart|pub)'

"L: python":
    - '(python|pip|poetry|uv|conda)'

"L: python:uv":
    - '(uv)'

"L: python:conda":
    - '(conda)'

"L: terraform":
    - '(terraform)'

"L: swift":
    - '(swift)'

"L: helm":
    - '(helm)'
