#!/bin/bash

set -e

install_dir=$1
if [ -z "$install_dir" ]; then
  echo "usage: $0 INSTALL_DIR"
  exit 1
fi

mix local.hex --force

helpers_dir="$(dirname "${BASH_SOURCE[0]}")"
cp -r \
  "$helpers_dir/lib" \
  "$helpers_dir/mix.exs" \
  "$helpers_dir/mix.lock" \
  "$install_dir"

cd "$install_dir"
mix deps.get
