AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Max: 80

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SignalException:
  EnforcedStyle: only_raise

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing
