# For all options see https://github.com/bbatsov/rubocop/tree/master/config

inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SignalException:
  EnforcedStyle: only_raise

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing
