AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Exclude:
    - vendor/**/*
    - bin/**/*
    - tmp/**/*
    - helpers/utils/git-credential-store-immutable

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/RescueEnsureAlignment:
  Enabled: false

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 80

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - dependabot-core.gemspec

Metrics/ParameterLists:
  CountKeywordArgs: false

Naming/FileName:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SignalException:
  EnforcedStyle: only_raise

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': ()
    '%I': ()
    '%w': ()
    '%W': ()
