AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - vendor/**/*
    - bin/**/*

Metrics/LineLength:
  Max: 80

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/EmptyLineAfterMagicComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SignalException:
  EnforcedStyle: only_raise

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': ()
    '%I': ()
    '%w': ()
    '%W': ()
