FROM dependabot/dependabot-core

USER dependabot
RUN pyenv install -s 3.6.13
RUN pyenv install -s 3.7.1
RUN pyenv install -s 3.7.10

RUN mkdir -p \
  /home/dependabot/dependabot-core/bundler \
  /home/dependabot/dependabot-core/cargo \
  /home/dependabot/dependabot-core/common \
  /home/dependabot/dependabot-core/composer \
  /home/dependabot/dependabot-core/dep \
  /home/dependabot/dependabot-core/docker \
  /home/dependabot/dependabot-core/elm \
  /home/dependabot/dependabot-core/git_submodules \
  /home/dependabot/dependabot-core/github_actions \
  /home/dependabot/dependabot-core/go_modules \
  /home/dependabot/dependabot-core/gradle \
  /home/dependabot/dependabot-core/hex \
  /home/dependabot/dependabot-core/maven \
  /home/dependabot/dependabot-core/npm_and_yarn \
  /home/dependabot/dependabot-core/nuget \
  /home/dependabot/dependabot-core/omnibus \
  /home/dependabot/dependabot-core/python \
  /home/dependabot/dependabot-core/terraform \
  /home/dependabot/dependabot-core/bundler/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/cargo/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/common/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/composer/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/dep/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/docker/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/elm/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/git_submodules/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/github_actions/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/go_modules/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/gradle/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/hex/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/maven/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/npm_and_yarn/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/nuget/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/omnibus/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/python/spec/fixtures/vcr_cassettes \
  /home/dependabot/dependabot-core/terraform/spec/fixtures/vcr_cassettes

RUN git config --global user.name dependabot-ci && \
  git config --global user.email no-reply@github.com
