FROM ghcr.io/dependabot/dependabot-updater-core

USER dependabot

# Configure cargo to use Git CLI so the Git shim works
RUN mkdir -p ~/.cargo && printf "[net]\ngit-fetch-with-cli = true\n" >> ~/.cargo/config.toml

COPY --chown=dependabot:dependabot cargo /home/dependabot/cargo
