#!/bin/bash

set -e

install_dir=$1
if [ -z "$install_dir" ]; then
  echo "usage: $0 INSTALL_DIR"
  exit 1
fi

helpers_dir="$(dirname "${BASH_SOURCE[0]}")"
cp -r \
  "$helpers_dir/lib" \
  "$helpers_dir/test" \
  "$helpers_dir/run.js" \
  "$helpers_dir/.eslintrc" \
  "$helpers_dir/jest.config.js" \
  "$helpers_dir/package.json" \
  "$helpers_dir/package-lock.json" \
  "$install_dir"

cd "$install_dir"
npm ci --no-audit --fetch-timeout=600000
