#!/bin/bash

set -e

install_dir=$1
if [ -z "$install_dir" ]; then
  echo "usage: $0 INSTALL_DIR"
  exit 1
fi

helpers_dir="$(dirname "${BASH_SOURCE[0]}")"
cp -r \
  "$helpers_dir/npm" \
  "$helpers_dir/yarn" \
  "$helpers_dir/package.json" \
  "$helpers_dir/yarn.lock" \
  "$install_dir"

cd "$install_dir"
yarn install
