#!/bin/sh

set -e

install_dir=$1
if [ -z "$install_dir" ]; then
  echo "usage: $0 INSTALL_DIR"
  exit 1
fi

if [ ! -d "$install_dir" ]; then
  mkdir -p "$install_dir"
fi

helpers_dir="$(dirname "$0")"
cp -r \
  "$helpers_dir/lib" \
  "$helpers_dir/test" \
  "$helpers_dir/run.js" \
  "$helpers_dir/package.json" \
  "$helpers_dir/yarn.lock" \
  "$install_dir"

cd "$install_dir"

case "$DEPENDABOT_ENV" in
"production")
  yarn install --production
  ;;
*)
  yarn install
  ;;
esac
