# frozen_string_literal: true

source "https://rubygems.org"

gem "dependabot-bundler", path: "../bundler"
gem "dependabot-cargo", path: "../cargo"
gem "dependabot-common", path: "../common"
gem "dependabot-composer", path: "../composer"
gem "dependabot-dep", path: "../dep"
gem "dependabot-docker", path: "../docker"
gem "dependabot-elm", path: "../elm"
gem "dependabot-github_actions", path: "../github_actions"
gem "dependabot-git_submodules", path: "../git_submodules"
gem "dependabot-go_modules", path: "../go_modules"
gem "dependabot-gradle", path: "../gradle"
gem "dependabot-hex", path: "../hex"
gem "dependabot-maven", path: "../maven"
gem "dependabot-npm_and_yarn", path: "../npm_and_yarn"
gem "dependabot-nuget", path: "../nuget"
gem "dependabot-python", path: "../python"
gem "dependabot-terraform", path: "../terraform"

gem "rubocop", group: :development

# Visual Studio Code integration
gem "debase", group: :development
gem "reek", group: :development
gem "ruby-debug-ide", group: :development
gem "solargraph", group: :development

gemspec
