# frozen_string_literal: true

source "https://rubygems.org"

gemspec path: "../bundler"
gemspec path: "../cargo"
gemspec path: "../common"
gemspec path: "../composer"
gemspec path: "../docker"
gemspec path: "../elm"
gemspec path: "../github_actions"
gemspec path: "../git_submodules"
gemspec path: "../go_modules"
gemspec path: "../gradle"
gemspec path: "../hex"
gemspec path: "../maven"
gemspec path: "../npm_and_yarn"
gemspec path: "../nuget"
gemspec path: "../pub"
gemspec path: "../python"
gemspec path: "../swift"
gemspec path: "../terraform"

# Visual Studio Code integration
gem "reek", group: :development
gem "solargraph", group: :development

# Sorbet
# This conditional is necessary because Sorbet does not support aarch64-linux (Docker on Apple Silicon) yet.
# See https://github.com/sorbet/sorbet/issues/4119
if RUBY_PLATFORM.include?("darwin") || RUBY_PLATFORM.include?("x86_64")
  gem "sorbet", group: :development
  gem "tapioca", require: false, group: :development
end

gemspec
