# typed: strong
# frozen_string_literal: true

module Dependabot
  module GithubActions
    # Reference to the GitHub.com domain
    GITHUB_COM = "github.com"

    # Regular expression to match a GitHub repository reference
    GITHUB_REPO_REFERENCE = %r{
            ^(?<owner>[\w.-]+)/
            (?<repo>[\w.-]+)
            (?<path>/[^\@]+)?
            @(?<ref>.+)
          }x

    # The ecosystem name for GitHub Actions
    ECOSYSTEM = "github_actions"

    # The pattern to match manifest files
    MANIFEST_FILE_PATTERN = /\.ya?ml$/
    # The name of the manifest file
    MANIFEST_FILE_YML = "action.yml"
    # The name of the manifest file
    MANIFEST_FILE_YAML = "action.yaml"
    # The pattern to match any .yml or .yaml file
    ANYTHING_YML = "<anything>.yml"
    # The path to the workflow directory
    WORKFLOW_DIRECTORY = ".github/workflows"
    # The path to the config .yml file
    CONFIG_YMLS = T.let("#{WORKFLOW_DIRECTORY}/#{ANYTHING_YML}".freeze, String)

    # The basename of the per-repo Actions lockfile generated by gh-actions-lock
    LOCKFILE_NAME = "actions.lock"
    # The repo-relative path to the Actions lockfile
    LOCKFILE_PATH = T.let("#{WORKFLOW_DIRECTORY}/#{LOCKFILE_NAME}".freeze, String)
    # The only lockfile schema version this ecosystem understands.
    SUPPORTED_LOCKFILE_VERSION = "v0.0.2"

    OWNER_KEY = "owner"
    REPO_KEY = "repo"
    PATH_KEY = "path"
    REF_KEY = "ref"
    USES_KEY = "uses"
    STEPS_KEY = "steps"
  end
end
