inherit_from: ../.rubocop.yml

Sorbet/ForbidTUnsafe:
  Exclude:
    - lib/dependabot/api_client.rb
    - lib/dependabot/base_command.rb
    - lib/dependabot/file_fetcher_command.rb
    - lib/dependabot/job.rb
    - lib/dependabot/service.rb
    - lib/dependabot/update_files_command.rb
    - lib/dependabot/update_graph_command.rb
    - lib/dependabot/updater/error_handler.rb
    - lib/dependabot/updater/group_dependency_selector.rb
    - lib/dependabot/updater/pattern_specificity_calculator.rb
