# frozen_string_literal: true

source "https://rubygems.org"

gem "dependabot-bun", path: "../bun"
gem "dependabot-bundler", path: "../bundler"
gem "dependabot-cargo", path: "../cargo"
gem "dependabot-common", path: "../common"
gem "dependabot-composer", path: "../composer"
gem "dependabot-devcontainers", path: "../devcontainers"
gem "dependabot-docker", path: "../docker"
gem "dependabot-docker_compose", path: "../docker_compose"
gem "dependabot-dotnet_sdk", path: "../dotnet_sdk"
gem "dependabot-elm", path: "../elm"
gem "dependabot-github_actions", path: "../github_actions"
gem "dependabot-git_submodules", path: "../git_submodules"
gem "dependabot-go_modules", path: "../go_modules"
gem "dependabot-gradle", path: "../gradle"
gem "dependabot-helm", path: "../helm"
gem "dependabot-hex", path: "../hex"
gem "dependabot-maven", path: "../maven"
gem "dependabot-npm_and_yarn", path: "../npm_and_yarn"
gem "dependabot-nuget", path: "../nuget"
gem "dependabot-pub", path: "../pub"
gem "dependabot-python", path: "../python"
gem "dependabot-silent", path: "../silent"
gem "dependabot-swift", path: "../swift"
gem "dependabot-terraform", path: "../terraform"
gem "dependabot-uv", path: "../uv"

gem "http", "~> 5.1"
gem "octokit", "7.2.0"
gem "opentelemetry-exporter-otlp", "~> 0.30"
gem "opentelemetry-exporter-otlp-logs", "~> 0.2"
gem "opentelemetry-exporter-otlp-metrics", "~> 0.4"
gem "opentelemetry-instrumentation-excon", "~> 0.23"
gem "opentelemetry-instrumentation-faraday", "~> 0.26"
gem "opentelemetry-instrumentation-http", "~> 0.24"
gem "opentelemetry-instrumentation-net_http", "~> 0.23"
gem "opentelemetry-logs-sdk", "~> 0.2"
gem "opentelemetry-metrics-sdk", "~> 0.6"
gem "opentelemetry-sdk", "~> 1.8"
gem "sentry-opentelemetry", "~> 5.23"
gem "sentry-ruby", "~> 5.23"
gem "terminal-table", "~> 3.0.2"

gem "flamegraph", "~> 0.9.5"

gem "zeitwerk", "~> 2.7"

group :test do
  common_gemspec = File.expand_path("../common/dependabot-common.gemspec", __dir__)

  Dir.chdir(File.dirname(common_gemspec)) do
    Gem::Specification.load(common_gemspec).development_dependencies.each do |dep|
      gem dep.name, *dep.requirement.as_list
    end
  end
end
