# frozen_string_literal: true

source "https://rubygems.org"

gem "dependabot-bundler", path: "../bundler"
gem "dependabot-cargo", path: "../cargo"
gem "dependabot-common", path: "../common"
gem "dependabot-composer", path: "../composer"
gem "dependabot-docker", path: "../docker"
gem "dependabot-elm", path: "../elm"
gem "dependabot-github_actions", path: "../github_actions"
gem "dependabot-git_submodules", path: "../git_submodules"
gem "dependabot-go_modules", path: "../go_modules"
gem "dependabot-gradle", path: "../gradle"
gem "dependabot-hex", path: "../hex"
gem "dependabot-maven", path: "../maven"
gem "dependabot-npm_and_yarn", path: "../npm_and_yarn"
gem "dependabot-nuget", path: "../nuget"
gem "dependabot-pub", path: "../pub"
gem "dependabot-python", path: "../python"
gem "dependabot-terraform", path: "../terraform"

gem "activesupport", "~> 6.1.4"
gem "http", "~> 5.1"
gem "octokit", "6.0.1"
gem "sentry-raven", "~> 3.1"
gem "terminal-table", "~> 3.0.2"

group :test do
  gem "debug", "~> 1.7.0"
  gem "rspec", "~> 3.12"
  gem "rubocop", "~> 1.39.0"
  gem "rubocop-performance", "~> 1.15.1"
  gem "vcr", "~> 6.1"
  gem "webmock", "~> 3.18"
end

group :development do
  gem "licensed", "~> 3.9", require: false
end
