# typed: false
# frozen_string_literal: true

require "spec_helper"
require "dependabot/python"

RSpec.describe Dependabot::Python::DependencyGrapher do
  subject(:grapher) do
    Dependabot::DependencyGraphers.for_package_manager("pip").new(
      file_parser: parser
    )
  end

  let(:pyproject_toml) do
    Dependabot::DependencyFile.new(
      name: "pyproject.toml",
      content: fixture("pyproject_files", "poetry_dependency_grapher.toml"),
      directory: "/"
    )
  end

  let(:pipfile) do
    Dependabot::DependencyFile.new(
      name: "Pipfile",
      content: fixture("pyproject_files", "pipenv_dependency_grapher.toml"),
      directory: "/"
    )
  end

  let(:dependency_files) { [pyproject_toml] }

  let(:requirements_in) do
    Dependabot::DependencyFile.new(
      name: "requirements.in",
      content: "requests==2.32.5\n",
      directory: "/"
    )
  end

  let(:requirements_txt) do
    Dependabot::DependencyFile.new(
      name: "requirements.txt",
      content: <<~TXT,
        # This file is autogenerated by pip-compile
        #    pip-compile --output-file=requirements.txt requirements.in
        requests==2.32.5
      TXT
      directory: "/"
    )
  end

  let(:setup_py) do
    Dependabot::DependencyFile.new(
      name: "setup.py",
      content: <<~PY,
        from setuptools import setup

        setup(name="example", version="0.1.0", install_requires=["requests==2.32.5"])
      PY
      directory: "/"
    )
  end

  let(:parser) do
    Dependabot::FileParsers.for_package_manager("pip").new(
      dependency_files: dependency_files,
      source: nil,
      credentials: [],
      reject_external_code: false
    )
  end

  describe "#relevant_dependency_file" do
    context "when poetry.lock is not present" do
      it "falls back to pyproject.toml" do
        expect(grapher.relevant_dependency_file).to eql(pyproject_toml)
      end
    end

    context "when poetry.lock is present" do
      let(:poetry_lock_file) do
        Dependabot::DependencyFile.new(
          name: "poetry.lock",
          content: fixture("dependency_grapher", "poetry_lock_with_relationships.lock"),
          directory: "/"
        )
      end

      let(:dependency_files) { [pyproject_toml, poetry_lock_file] }

      it "specifies the poetry.lock as the relevant dependency file" do
        expect(grapher.relevant_dependency_file).to eql(poetry_lock_file)
      end
    end

    context "when both pyproject.toml and Pipfile are present" do
      let(:dependency_files) { [pyproject_toml, pipfile] }

      it "prefers pyproject.toml over Pipfile" do
        expect(grapher.relevant_dependency_file).to eql(pyproject_toml)
      end
    end

    context "when Pipfile is present without Pipfile.lock" do
      let(:dependency_files) { [pipfile] }

      it "falls back to Pipfile" do
        expect(grapher.relevant_dependency_file).to eql(pipfile)
      end
    end

    context "when Pipfile and Pipfile.lock are present" do
      let(:pipfile_lock_file) do
        Dependabot::DependencyFile.new(
          name: "Pipfile.lock",
          content: fixture("dependency_grapher", "pipfile_lock_with_dependencies.json"),
          directory: "/"
        )
      end

      let(:dependency_files) { [pipfile, pipfile_lock_file] }

      it "specifies the Pipfile.lock as the relevant dependency file" do
        expect(grapher.relevant_dependency_file).to eql(pipfile_lock_file)
      end
    end

    context "when requirements files indicate pip-compile" do
      context "when requirements.in and matching requirements.txt are present" do
        let(:dependency_files) { [requirements_in, requirements_txt] }

        it "prefers requirements.txt as the lockfile representation" do
          expect(grapher.relevant_dependency_file).to eql(requirements_txt)
        end
      end

      context "when only requirements.in is present" do
        let(:dependency_files) { [requirements_in] }

        it "falls back to requirements.in" do
          expect(grapher.relevant_dependency_file).to eql(requirements_in)
        end
      end
    end

    context "when both poetry and pipenv lockfiles are present" do
      let(:poetry_lock_file) do
        Dependabot::DependencyFile.new(
          name: "poetry.lock",
          content: fixture("dependency_grapher", "poetry_lock_with_relationships.lock"),
          directory: "/"
        )
      end

      let(:pipfile_lock_file) do
        Dependabot::DependencyFile.new(
          name: "Pipfile.lock",
          content: fixture("dependency_grapher", "pipfile_lock_with_dependencies.json"),
          directory: "/"
        )
      end

      let(:dependency_files) { [pyproject_toml, poetry_lock_file, pipfile, pipfile_lock_file] }

      it "uses parser package manager detection precedence" do
        expect(grapher.relevant_dependency_file).to eql(pipfile_lock_file)
      end
    end

    context "when only setup.py is present" do
      let(:dependency_files) { [setup_py] }

      it "falls back to setup.py for pip" do
        expect(grapher.relevant_dependency_file).to eql(setup_py)
      end
    end

    context "when a requirements.txt contains dependencies with extras" do
      let(:requirements_txt_with_extras) do
        Dependabot::DependencyFile.new(
          name: "requirements.txt",
          content: "cachecontrol[filecache]==0.14.2\nrequests==2.32.5\n",
          directory: "/"
        )
      end

      let(:dependency_files) { [requirements_txt_with_extras] }

      it "falls back to requirements.txt" do
        expect(grapher.relevant_dependency_file).to eql(requirements_txt_with_extras)
      end
    end
  end

  describe "#resolved_dependencies" do
    context "when poetry.lock is present" do
      let(:poetry_lock_file) do
        Dependabot::DependencyFile.new(
          name: "poetry.lock",
          content: fixture("dependency_grapher", "poetry_lock_with_relationships.lock"),
          directory: "/"
        )
      end

      let(:dependency_files) { [pyproject_toml, poetry_lock_file] }

      it "extracts dependency relationships from the lockfile" do
        resolved_dependencies = grapher.resolved_dependencies

        expect(resolved_dependencies.fetch("pkg:pypi/flask@3.1.3").dependencies).to eq(
          [
            "pkg:pypi/blinker@1.9.0",
            "pkg:pypi/click@8.3.1",
            "pkg:pypi/itsdangerous@2.2.0",
            "pkg:pypi/jinja2@3.1.6",
            "pkg:pypi/markupsafe@3.0.3",
            "pkg:pypi/werkzeug@3.1.6"
          ]
        )
      end

      it "parses lockfile relationships for requests" do
        resolved_dependencies = grapher.resolved_dependencies

        expect(resolved_dependencies.fetch("pkg:pypi/requests@2.32.5").dependencies).to eq(
          [
            "pkg:pypi/certifi@2026.2.25",
            "pkg:pypi/charset-normalizer@3.4.4",
            "pkg:pypi/idna@3.11",
            "pkg:pypi/urllib3@2.6.3"
          ]
        )
      end

      it "serializes dependencies with relationship data" do
        resolved_dependencies = grapher.resolved_dependencies

        expect(resolved_dependencies.keys).to include(
          "pkg:pypi/flask@3.1.3",
          "pkg:pypi/requests@2.32.5",
          "pkg:pypi/ruff@0.15.4",
          "pkg:pypi/markupsafe@3.0.3"
        )

        flask = resolved_dependencies.fetch("pkg:pypi/flask@3.1.3")
        expect(flask.direct).to be(true)
        expect(flask.runtime).to be(true)

        markupsafe = resolved_dependencies.fetch("pkg:pypi/markupsafe@3.0.3")
        expect(markupsafe.direct).to be(false)
        expect(markupsafe.dependencies).to eq([])
      end
    end

    context "when poetry.lock is not present" do
      let(:lockfile_generator) do
        instance_double(
          Dependabot::Python::DependencyGrapher::LockfileGenerator,
          generate: nil
        )
      end

      before do
        allow(Dependabot::Python::DependencyGrapher::LockfileGenerator)
          .to receive(:new).and_return(lockfile_generator)
      end

      it "attempts to generate an ephemeral lockfile" do
        grapher.resolved_dependencies
        expect(Dependabot::Python::DependencyGrapher::LockfileGenerator)
          .to have_received(:new).with(
            dependency_files: dependency_files,
            credentials: []
          )
        expect(lockfile_generator).to have_received(:generate)
      end

      context "when lockfile generation fails" do
        it "sets the errored_fetching_subdependencies flag" do
          grapher.resolved_dependencies

          expect(grapher.errored_fetching_subdependencies).to be(true)
        end

        it "returns dependencies without relationship data" do
          resolved_dependencies = grapher.resolved_dependencies

          resolved_dependencies.each_value do |dep|
            expect(dep.dependencies).to eq([])
          end
        end

        it "returns PURLs without resolved versions" do
          resolved_dependencies = grapher.resolved_dependencies

          expect(resolved_dependencies.keys).to include(
            "pkg:pypi/flask",
            "pkg:pypi/requests",
            "pkg:pypi/ruff"
          )
        end
      end

      context "when lockfile generation raises an error" do
        let(:lockfile_generator) do
          instance_double(
            Dependabot::Python::DependencyGrapher::LockfileGenerator
          ).tap do |gen|
            allow(gen).to receive(:generate).and_raise(
              Dependabot::SharedHelpers::HelperSubprocessFailed.new(
                message: "poetry lock failed: authentication required",
                error_context: {}
              )
            )
          end
        end

        it "sets the error flag for degraded status" do
          grapher.resolved_dependencies

          expect(grapher.errored_fetching_subdependencies).to be(true)
        end

        it "preserves the original error as the subdependency error" do
          grapher.resolved_dependencies

          expect(grapher.subdependency_error).to be_a(Dependabot::SharedHelpers::HelperSubprocessFailed)
          expect(grapher.subdependency_error.message).to include("poetry lock failed")
        end

        it "returns dependencies without relationship data" do
          resolved_dependencies = grapher.resolved_dependencies

          resolved_dependencies.each_value do |dep|
            expect(dep.dependencies).to eq([])
          end
        end
      end

      context "when lockfile generation succeeds" do
        let(:ephemeral_lockfile) do
          Dependabot::DependencyFile.new(
            name: "poetry.lock",
            content: fixture("dependency_grapher", "poetry_lock_with_relationships.lock"),
            directory: "/"
          )
        end

        let(:lockfile_generator) do
          instance_double(
            Dependabot::Python::DependencyGrapher::LockfileGenerator,
            generate: ephemeral_lockfile
          )
        end

        it "injects the ephemeral lockfile and uses it for relationship data" do
          resolved_dependencies = grapher.resolved_dependencies

          expect(resolved_dependencies.fetch("pkg:pypi/flask@3.1.3").dependencies).to eq(
            [
              "pkg:pypi/blinker@1.9.0",
              "pkg:pypi/click@8.3.1",
              "pkg:pypi/itsdangerous@2.2.0",
              "pkg:pypi/jinja2@3.1.6",
              "pkg:pypi/markupsafe@3.0.3",
              "pkg:pypi/werkzeug@3.1.6"
            ]
          )
        end

        it "resolves exact versions from the generated lockfile" do
          resolved_dependencies = grapher.resolved_dependencies

          expect(resolved_dependencies.keys).to include(
            "pkg:pypi/flask@3.1.3",
            "pkg:pypi/requests@2.32.5",
            "pkg:pypi/ruff@0.15.4"
          )
        end

        it "reports pyproject.toml as the relevant dependency file, not the ephemeral lockfile" do
          grapher.resolved_dependencies
          expect(grapher.relevant_dependency_file).to eql(pyproject_toml)
        end
      end
    end

    context "when poetry.lock is corrupt" do
      let(:poetry_lock_file) do
        Dependabot::DependencyFile.new(
          name: "poetry.lock",
          content: "invalid toml content {{{",
          directory: "/"
        )
      end

      let(:dependency_files) { [pyproject_toml, poetry_lock_file] }

      it "raises a DependencyFileNotParseable error" do
        expect { grapher.resolved_dependencies }.to raise_error(Dependabot::DependencyFileNotParseable)
      end
    end

    context "when Pipfile and Pipfile.lock are present" do
      let(:pipfile_lock_file) do
        Dependabot::DependencyFile.new(
          name: "Pipfile.lock",
          content: fixture("dependency_grapher", "pipfile_lock_with_dependencies.json"),
          directory: "/"
        )
      end

      let(:dependency_files) { [pipfile, pipfile_lock_file] }

      context "when pipenv graph returns relationship data" do
        let(:pipenv_runner) { instance_double(Dependabot::Python::PipenvRunner) }

        before do
          allow(Dependabot::Python::PipenvRunner).to receive(:new).and_return(pipenv_runner)
          allow(pipenv_runner).to receive(:run_pipenv_graph)
            .and_return(fixture("dependency_grapher", "pipenv_graph_output.json"))
        end

        it "extracts dependency relationships from pipenv graph output" do
          resolved_dependencies = grapher.resolved_dependencies

          expect(resolved_dependencies.fetch("pkg:pypi/requests@2.32.5").dependencies).to eq(
            [
              "pkg:pypi/certifi@2024.2.2",
              "pkg:pypi/charset-normalizer@3.3.2",
              "pkg:pypi/idna@3.6",
              "pkg:pypi/urllib3@2.2.1"
            ]
          )
        end

        it "marks direct and transitive dependencies correctly" do
          resolved_dependencies = grapher.resolved_dependencies

          requests = resolved_dependencies.fetch("pkg:pypi/requests@2.32.5")
          expect(requests.direct).to be(true)

          charset_normalizer = resolved_dependencies.fetch("pkg:pypi/charset-normalizer@3.3.2")
          expect(charset_normalizer.direct).to be(false)
          expect(charset_normalizer.dependencies).to eq([])
        end
      end

      context "when pipenv graph fails" do
        let(:pipenv_graph_error) { StandardError.new("pipenv sync failed: could not install packages") }
        let(:pipenv_runner) { instance_double(Dependabot::Python::PipenvRunner) }

        before do
          allow(Dependabot::Python::PipenvRunner).to receive(:new).and_return(pipenv_runner)
          allow(pipenv_runner).to receive(:run_pipenv_graph).and_raise(pipenv_graph_error)
        end

        it "sets the error flag without raising" do
          grapher.resolved_dependencies

          expect(grapher.errored_fetching_subdependencies).to be(true)
        end

        it "assigns the original error to the grapher" do
          grapher.resolved_dependencies

          expect(grapher.subdependency_error).to eql(pipenv_graph_error)
        end

        it "returns empty dependencies for all resolved packages" do
          depends_on_values = grapher.resolved_dependencies.map { |_, dep| dep.dependencies }

          expect(depends_on_values).to all(be_empty)
        end
      end

      context "when pipenv graph returns malformed JSON" do
        let(:pipenv_runner) { instance_double(Dependabot::Python::PipenvRunner) }

        before do
          allow(Dependabot::Python::PipenvRunner).to receive(:new).and_return(pipenv_runner)
          allow(pipenv_runner).to receive(:run_pipenv_graph).and_return("not valid json {{{")
        end

        it "returns empty dependencies for all resolved packages without raising" do
          depends_on_values = grapher.resolved_dependencies.map { |_, dep| dep.dependencies }

          expect(depends_on_values).to all(be_empty)
        end

        it "does not set the error flag" do
          grapher.resolved_dependencies

          expect(grapher.errored_fetching_subdependencies).to be(false)
        end
      end
    end

    context "when Pipfile is present without Pipfile.lock" do
      let(:dependency_files) { [pipfile] }

      it "returns dependencies without relationship data" do
        resolved_dependencies = grapher.resolved_dependencies

        expect(resolved_dependencies.keys).to include(
          "pkg:pypi/requests@2.32.5",
          "pkg:pypi/certifi@2024.2.2",
          "pkg:pypi/ruff@0.15.4"
        )

        resolved_dependencies.each_value do |dep|
          expect(dep.dependencies).to eq([])
        end
      end
    end

    context "when both poetry.lock and Pipfile.lock are present" do
      let(:poetry_lock_file) do
        Dependabot::DependencyFile.new(
          name: "poetry.lock",
          content: fixture("dependency_grapher", "poetry_lock_with_relationships.lock"),
          directory: "/"
        )
      end

      let(:pipfile_lock_file) do
        Dependabot::DependencyFile.new(
          name: "Pipfile.lock",
          content: fixture("dependency_grapher", "pipfile_lock_with_dependencies.json"),
          directory: "/"
        )
      end

      let(:dependency_files) { [pyproject_toml, poetry_lock_file, pipfile, pipfile_lock_file] }
      let(:pipenv_runner) { instance_double(Dependabot::Python::PipenvRunner) }

      before do
        allow(Dependabot::Python::PipenvRunner).to receive(:new).and_return(pipenv_runner)
        allow(pipenv_runner).to receive(:run_pipenv_graph)
          .and_return(fixture("dependency_grapher", "pipenv_graph_output.json"))
      end

      it "uses pipenv graph relationships based on parser package manager precedence" do
        resolved_dependencies = grapher.resolved_dependencies

        expect(resolved_dependencies.fetch("pkg:pypi/requests@2.32.5").dependencies).to eq(
          [
            "pkg:pypi/certifi@2024.2.2",
            "pkg:pypi/charset-normalizer@3.3.2",
            "pkg:pypi/idna@3.6",
            "pkg:pypi/urllib3@2.2.1"
          ]
        )
      end
    end

    context "when dependencies have extras in their names" do
      let(:requirements_txt_with_extras) do
        Dependabot::DependencyFile.new(
          name: "requirements.txt",
          content: "cachecontrol[filecache]==0.14.2\nrequests==2.32.5\n",
          directory: "/"
        )
      end

      let(:dependency_files) { [requirements_txt_with_extras] }

      it "strips extras from PURL names" do
        resolved_dependencies = grapher.resolved_dependencies

        purl_keys = resolved_dependencies.keys
        expect(purl_keys).to include("pkg:pypi/cachecontrol@0.14.2")
        expect(purl_keys).not_to include("pkg:pypi/cachecontrol[filecache]@0.14.2")
      end
    end

    context "when PEP 621 + Poetry project has extras dependencies" do
      let(:pep621_poetry_toml) do
        Dependabot::DependencyFile.new(
          name: "pyproject.toml",
          content: fixture("pyproject_files", "pep621_poetry_with_extras.toml"),
          directory: "/"
        )
      end

      let(:pep621_poetry_lock) do
        Dependabot::DependencyFile.new(
          name: "poetry.lock",
          content: fixture("dependency_grapher", "pep621_poetry_with_extras.lock"),
          directory: "/"
        )
      end

      let(:dependency_files) { [pep621_poetry_toml, pep621_poetry_lock] }

      it "includes the versioned PURL without a duplicate versionless entry" do
        resolved_dependencies = grapher.resolved_dependencies

        expect(resolved_dependencies.keys).to include("pkg:pypi/cachecontrol@0.14.4")
        expect(resolved_dependencies.keys).not_to include("pkg:pypi/cachecontrol")
      end
    end
  end
end
