# typed: false
# frozen_string_literal: true

require "spec_helper"
require "dependabot/python"
require "dependabot/python/pip_compile_options_parser"

RSpec.describe Dependabot::Python::PipCompileOptionsParser do
  subject(:parser) { described_class.new(compiled_file) }

  let(:compiled_file) do
    Dependabot::DependencyFile.new(
      name: "requirements.txt",
      content: compiled_content,
      directory: "/"
    )
  end

  describe "#options_from_compiled_file" do
    context "with a minimal compiled file" do
      let(:compiled_content) do
        <<~TXT
          #
          # This file is autogenerated by pip-compile with Python 3.9
          # by the following command:
          #
          #    pip-compile --output-file=requirements.txt requirements.in
          #
          requests==2.32.5
              # via -r requirements.in
        TXT
      end

      it "includes the output-file option" do
        expect(parser.options_from_compiled_file).to include("--output-file=requirements.txt")
      end

      it "does not include --generate-hashes" do
        expect(parser.options_from_compiled_file).not_to include("--generate-hashes")
      end

      it "does not include --allow-unsafe" do
        expect(parser.options_from_compiled_file).not_to include("--allow-unsafe")
      end

      it "does not include --no-header" do
        expect(parser.options_from_compiled_file).not_to include("--no-header")
      end

      it "does not include --no-annotate" do
        expect(parser.options_from_compiled_file).not_to include("--no-annotate")
      end
    end

    context "with generate-hashes enabled" do
      let(:compiled_content) do
        <<~TXT
          #
          # This file is autogenerated by pip-compile with Python 3.9
          #
          requests==2.32.5 \
              --hash=sha256:abc123
              # via -r requirements.in
        TXT
      end

      it "includes --generate-hashes" do
        expect(parser.options_from_compiled_file).to include("--generate-hashes")
      end
    end

    context "with unsafe packages" do
      let(:compiled_content) do
        <<~TXT
          #
          # This file is autogenerated by pip-compile with Python 3.9
          #
          setuptools==70.0.0
              # via some-package
          requests==2.32.5
              # via -r requirements.in
        TXT
      end

      it "includes --allow-unsafe" do
        expect(parser.options_from_compiled_file).to include("--allow-unsafe")
      end
    end

    context "without annotation comments" do
      let(:compiled_content) do
        <<~TXT
          #
          # This file is autogenerated by pip-compile with Python 3.9
          #
          requests==2.32.5
        TXT
      end

      it "includes --no-annotate" do
        expect(parser.options_from_compiled_file).to include("--no-annotate")
      end
    end

    context "without autogenerated header" do
      let(:compiled_content) do
        <<~TXT
          requests==2.32.5
              # via -r requirements.in
        TXT
      end

      it "includes --no-header" do
        expect(parser.options_from_compiled_file).to include("--no-header")
      end
    end

    context "with pre-release packages" do
      let(:compiled_content) do
        <<~TXT
          #
          # This file is autogenerated by pip-compile with Python 3.9
          #    pip-compile --pre --output-file=requirements.txt requirements.in
          #
          requests==3.0.0b1
              # via -r requirements.in
        TXT
      end

      it "includes --pre" do
        expect(parser.options_from_compiled_file).to include("--pre")
      end
    end

    context "with strip-extras" do
      let(:compiled_content) do
        <<~TXT
          #
          # This file is autogenerated by pip-compile with Python 3.9
          #    pip-compile --strip-extras --output-file=requirements.txt requirements.in
          #
          requests==2.32.5
              # via -r requirements.in
        TXT
      end

      it "includes --strip-extras" do
        expect(parser.options_from_compiled_file).to include("--strip-extras")
      end
    end

    context "with backtracking resolver" do
      let(:compiled_content) do
        <<~TXT
          #
          # This file is autogenerated by pip-compile with Python 3.9
          #    pip-compile --resolver=backtracking --output-file=requirements.txt requirements.in
          #
          requests==2.32.5
              # via -r requirements.in
        TXT
      end

      it "includes --resolver=backtracking" do
        expect(parser.options_from_compiled_file).to include("--resolver=backtracking")
      end
    end

    context "with index-url in content" do
      let(:compiled_content) do
        <<~TXT
          #
          # This file is autogenerated by pip-compile with Python 3.9
          #
          # index-url https://pypi.org/simple
          requests==2.32.5
              # via -r requirements.in
        TXT
      end

      it "does not include --no-emit-index-url" do
        expect(parser.options_from_compiled_file).not_to include("--no-emit-index-url")
      end
    end

    context "without index-url in content" do
      let(:compiled_content) do
        <<~TXT
          #
          # This file is autogenerated by pip-compile with Python 3.9
          #
          requests==2.32.5
              # via -r requirements.in
        TXT
      end

      it "includes --no-emit-index-url" do
        expect(parser.options_from_compiled_file).to include("--no-emit-index-url")
      end
    end
  end
end
