# frozen_string_literal: true

source "https://rubygems.org"

gem "elasticsearch-dsl",
    github: "dependabot-fixtures/elasticsearch-ruby",
    branch: "5.x",
    require: "dependabot-fixtures/dsl"
gem "elasticsearch-model", github: "dependabot-fixtures/elasticsearch-rails", branch: "5.x"
gem "elasticsearch-rails", github: "dependabot-fixtures/elasticsearch-rails", branch: "5.x"
