# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Add sentry gems
gem 'sentry-rails', '~> 5.10'
gem 'sentry-ruby', '~> 5.10'

# Add a gem from a git source
gem 'mocha', github: 'freerange/mocha'
