# frozen_string_literal: true
source "https://rubygems.org"

<<<<<<<< HEAD:bundler/spec/fixtures/projects/bundler2/git_source_internal/Gemfile
gem "parallel", git: "git@github.com:dependabot-fixtures/parallel", ref: "v1.12.0"
========
gem "business", github: "dependabot-fixtures/business"
>>>>>>>> origin/main:bundler/spec/fixtures/projects/bundler2/github_source/Gemfile
gem "statesman", "~> 1.2.0"
