#!/usr/bin/env bash

set -e

bundle install
bundle exec turbo_tests2 --verbose

# TODO: If you have native helpers or additional tests, add them here
# Example:
# cd /opt/apm && npm run lint && cd -
# cd /opt/apm && npm test && cd -
