inherit_from: ../.rubocop.yml

Sorbet/ForbidTUnsafe:
  Exclude:
    - lib/dependabot/npm_and_yarn/file_updater.rb
    - lib/dependabot/npm_and_yarn/file_updater/pnpm_lockfile_updater.rb
    - lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb
    - lib/dependabot/npm_and_yarn/update_checker.rb
    - lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb
    - lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb
