module Dependabot
  class PullRequestCreator
    class Codecommit
      attr_reader source: untyped

      attr_reader branch_name: untyped

      attr_reader base_commit: untyped

      attr_reader credentials: untyped

      attr_reader files: untyped

      attr_reader commit_message: untyped

      attr_reader pr_description: untyped

      attr_reader pr_name: untyped

      attr_reader author_details: untyped

      attr_reader labeler: untyped

      def initialize: (source: untyped source, branch_name: untyped branch_name, base_commit: untyped base_commit, credentials: untyped credentials, files: untyped files, commit_message: untyped commit_message, pr_description: untyped pr_description, pr_name: untyped pr_name, author_details: untyped author_details, labeler: untyped labeler, require_up_to_date_base: untyped require_up_to_date_base) -> void

      def create: () -> (nil | untyped)

      private

      def require_up_to_date_base?: () -> untyped

      def base_commit_is_up_to_date?: () -> untyped

      def create_pull_request: () -> (nil | untyped)

      def create_or_get_branch: (untyped commit) -> untyped

      def create_branch: (untyped commit) -> untyped

      def codecommit_client_for_source: () -> untyped

      def branch_exists?: (untyped branch_name) -> untyped

      def unmerged_pull_request_exists?: () -> untyped

      def pull_requests_for_branch: () -> untyped

      def create_commit: () -> untyped

      def default_branch: () -> untyped
    end
  end
end
