require "./app/boot"
require "./app/workers/dependency_file_fetcher"
require "./app/workers/dependency_file_parser"
require "./app/workers/update_checker"
require "./app/workers/dependency_file_updater"
require "./app/workers/pull_request_creator"
