require "bumper/workers/dependency_file_fetcher"
require "bumper/workers/dependency_file_parser"
require "bumper/workers/update_checker"
require "bumper/workers/dependency_file_updater"
require "bumper/workers/pull_request_creator"
