name = "DependabotHelper"
uuid = "4c4b75a0-81e9-11ee-a506-6b70a314a9a5"
authors = ["Dependabot <support@dependabot.com>", "contributors"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Pkg = "1"
JSON = "0.21"
julia = "1"
