module Dependabot
  module MetadataFinders
    def self.for_package_manager: (untyped package_manager) -> untyped

    def self.register: (untyped package_manager, untyped metadata_finder) -> untyped
  end
end
