#!/usr/bin/env bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NUGET_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# PowerShell unit tests
pwsh "$NUGET_DIR/updater/test.ps1"

# C# unit tests
"$SCRIPT_DIR/run-csharp-tests"
