#!/bin/bash
# shellcheck disable=all

native_experiment_value=$(cat "$DEPENDABOT_JOB_PATH" | jq '.job.experiments | with_entries(.key |= sub("-";"_";"g")) .nuget_native_updater')
echo "NuGet native updater experiment value: $native_experiment_value"

if [ "$native_experiment_value" == "true" ]; then
    pwsh "$DEPENDABOT_HOME/dependabot-updater/bin/main.ps1" $*
else
    "$DEPENDABOT_HOME/dependabot-updater/bin/run-original" $*
fi
