module Dependabot
  module Config
    class FileFetcher < Dependabot::FileFetchers::Base
      CONFIG_FILE_PATHS: ::Array[::String]

      def self.required_files_in?: (::Array[String] filenames) -> bool

      def self.required_files_message: () -> ::String

      def config_file: () -> untyped

      private

      def fetch_files: () -> untyped
    end
  end
end
