#!/bin/bash

set -e

install_dir=$1
if [ -z "$install_dir" ]; then
  echo "usage: $0 INSTALL_DIR"
  exit 1
fi

helpers_dir="$(dirname "${BASH_SOURCE[0]}")"
cp -r \
  "$helpers_dir/lib" \
  "$helpers_dir/run.py" \
  "$helpers_dir/requirements_py2.txt" \
  "$helpers_dir/requirements.txt" \
  "$install_dir"

cd "$install_dir"
PYENV_VERSION=2.7.18 pyenv exec pip install -r "requirements_py2.txt"
PYENV_VERSION=3.6.13  CRYPTOGRAPHY_DONT_BUILD_RUST=1 pyenv exec pip install -r "requirements.txt"
PYENV_VERSION=3.7.10  pyenv exec pip install -r "requirements.txt"
PYENV_VERSION=3.8.8   pyenv exec pip install -r "requirements.txt"
PYENV_VERSION=3.9.2   pyenv exec pip install -r "requirements.txt"
