#!/bin/bash

set -e

if [ -z "$DEPENDABOT_NATIVE_HELPERS_PATH" ]; then
  echo "Unable to build, DEPENDABOT_NATIVE_HELPERS_PATH is not set"
  exit 1
fi

install_dir="$DEPENDABOT_NATIVE_HELPERS_PATH/python"
mkdir -p "$install_dir"

helpers_dir="$(dirname "${BASH_SOURCE[0]}")"
cp -r \
  "$helpers_dir/lib" \
  "$helpers_dir/run.py" \
  "$helpers_dir/requirements.txt" \
  "$install_dir"

cd "$install_dir"
PYENV_VERSION=3.10.5 pyenv exec pip install -r "requirements.txt"

# Workaround of https://github.com/python-poetry/poetry/issues/3010
# By default poetry config file is stored under ~/.config/pypoetry
# and is not bound to any specific Python version
PYENV_VERSION=3.10.5 pyenv exec poetry config experimental.new-installer false
