module Dependabot
  module GitSubmodules
    class FileParser < Dependabot::FileParsers::Base
      def parse: () -> ::Array[Dependabot::Dependency]

      private

      def absolute_url: (::String url) -> ::String

      def submodule_sha: (::String path) -> ::String

      def gitmodules_file: () -> ::String

      def check_required_files: () -> void
    end
  end
end
