# frozen_string_literal: true

source "https://rubygems.org"

# NOTE: Used to run native helper specs
# group :test do
#   gem "byebug", "11.1.3"
#   gem "rspec", "3.10.0"
#   gem "rspec-its", "1.3.0"
#   gem "vcr", "6.0.0"
#   gem "webmock", "3.12.1"
# end
