# [Choice] Ubuntu version: ubuntu26.04, ubuntu24.04, ubuntu22.04
ARG VARIANT="ubuntu26.04"
FROM mcr.microsoft.com/devcontainers/base:${VARIANT}

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>


