#!/usr/bin/env bash

if [[ -z "$1" ]]; then
  echo "Usage: $0 <ecosystem>"
  exit 1
fi

set -e
cd "$(dirname "$0")/.."
source script/_common

export OMNIBUS_VERSION="latest"

if [[ "${USE_NIX:-}" == "1" ]]; then
  nix_build "$1"
else
  docker_build "$1"
fi
