#!/usr/bin/env bash

if [[ -z "$1" ]]; then
  echo "Usage: $0 <ecosystem>"
  exit 1
fi

set -e
cd "$(dirname "$0")/.."
source script/_common

export OMNIBUS_VERSION="latest"

echo "Building with Nix"
nix_build "$1"
