#!/usr/bin/env bash

if [[ -z "$1" ]]; then
  echo "Usage: $0 <ecosystem>"
  exit 1
fi

set -e
cd "$(dirname "$0")/.."
source script/_common

docker -v
echo "BuildKit: DOCKER_BUILDKIT=$DOCKER_BUILDKIT"

export OMNIBUS_VERSION="latest"
docker_build "$1"
