#!/bin/bash

dependabot "$@" \
  -v "$(pwd)"/.core-bash_history:/home/dependabot/.bash_history \
  -v "$(pwd)"/updater/bin:/home/dependabot/dependabot-updater/bin \
  -v "$(pwd)"/updater/lib:/home/dependabot/dependabot-updater/lib \
  -v "$(pwd)"/bin:/home/dependabot/bin \
  -v "$(pwd)"/bundler:/home/dependabot/bundler \
  -v "$(pwd)"/cargo:/home/dependabot/cargo \
  -v "$(pwd)"/common:/home/dependabot/common \
  -v "$(pwd)"/composer:/home/dependabot/composer \
  -v "$(pwd)"/docker:/home/dependabot/docker \
  -v "$(pwd)"/elm:/home/dependabot/elm \
  -v "$(pwd)"/git_submodules:/home/dependabot/git_submodules \
  -v "$(pwd)"/github_actions:/home/dependabot/github_actions \
  -v "$(pwd)"/go_modules:/home/dependabot/go_modules \
  -v "$(pwd)"/gradle:/home/dependabot/gradle \
  -v "$(pwd)"/hex:/home/dependabot/hex \
  -v "$(pwd)"/maven:/home/dependabot/maven \
  -v "$(pwd)"/npm_and_yarn:/home/dependabot/npm_and_yarn \
  -v "$(pwd)"/nuget:/home/dependabot/nuget \
  -v "$(pwd)"/pub:/home/dependabot/pub \
  -v "$(pwd)"/python:/home/dependabot/python \
  -v "$(pwd)"/terraform:/home/dependabot/terraform
