#!/bin/bash

dependabot "$@" \
  -v "$(pwd)"/.core-bash_history:/home/dependabot/.bash_history:delegated \
  -v "$(pwd)"/updater/bin:/home/dependabot/dependabot-updater/bin:delegated \
  -v "$(pwd)"/updater/lib:/home/dependabot/dependabot-updater/lib:delegated \
  -v "$(pwd)"/bin:/home/dependabot/bin:delegated \
  -v "$(pwd)"/bundler:/home/dependabot/bundler:delegated \
  -v "$(pwd)"/cargo:/home/dependabot/cargo:delegated \
  -v "$(pwd)"/common:/home/dependabot/common:delegated \
  -v "$(pwd)"/composer:/home/dependabot/composer:delegated \
  -v "$(pwd)"/docker:/home/dependabot/docker:delegated \
  -v "$(pwd)"/elm:/home/dependabot/elm:delegated \
  -v "$(pwd)"/git_submodules:/home/dependabot/git_submodules:delegated \
  -v "$(pwd)"/github_actions:/home/dependabot/github_actions:delegated \
  -v "$(pwd)"/go_modules:/home/dependabot/go_modules:delegated \
  -v "$(pwd)"/gradle:/home/dependabot/gradle:delegated \
  -v "$(pwd)"/hex:/home/dependabot/hex:delegated \
  -v "$(pwd)"/maven:/home/dependabot/maven:delegated \
  -v "$(pwd)"/npm_and_yarn:/home/dependabot/npm_and_yarn:delegated \
  -v "$(pwd)"/nuget:/home/dependabot/nuget:delegated \
  -v "$(pwd)"/pub:/home/dependabot/pub:delegated \
  -v "$(pwd)"/python:/home/dependabot/python:delegated \
  -v "$(pwd)"/terraform:/home/dependabot/terraform:delegated
