# frozen_string_literal: true

source "https://rubygems.org"

gemspec

install_if -> { RUBY_PLATFORM.include?("darwin") || RUBY_PLATFORM.include?("x86_64") } do
  gem "sorbet", group: :development
  gem "tapioca", require: false, group: :development
end
