# frozen_string_literal: true

source "https://rubygems.org"

gem "dummy-pkg-a", "~> 2.0.0"
gem "dummy-git-dependency", git: "git@github.com:dependabot-fixtures/ruby-dummy-git-dependency.git", ref: "v1.0.0"
