#!/bin/bash

set -e

install_dir=$1
if [ -z "$install_dir" ]; then
  echo "usage: $0 INSTALL_DIR"
  exit 1
fi

helpers_dir="$(dirname "${BASH_SOURCE[0]}")"
cp -r \
  "$helpers_dir/bin" \
  "$helpers_dir/src" \
  "$helpers_dir/.php-cs-fixer.php" \
  "$helpers_dir/composer.json" \
  "$helpers_dir/composer.lock" \
  "$helpers_dir/phpstan.neon" \
  "$install_dir"

cd "$install_dir"

composer validate --no-check-publish
composer install
composer run lint -- --dry-run
composer run stan

# Composer caches source zips and repo metadata, none of which is useful. Save space in this layer
rm -Rf ~/.composer/cache
