#!/bin/sh

set -e

install_dir=$1
if [ -z "$install_dir" ]; then
  echo "usage: $0 INSTALL_DIR"
  exit 1
fi

helpers_dir="$(dirname "$0")"
cd "$helpers_dir"

case "$DEPENDABOT_ENV" in
"production")
  composer install --no-dev --prefer-dist --optimize-autoloader
  ;;
*)
  composer validate --no-check-publish
  composer install
  composer run lint -- --dry-run
  composer run stan
  ;;
esac
