module Dependabot
  module Clients
    class BitbucketWithRetries
      RETRYABLE_ERRORS: untyped

      def self.for_bitbucket_dot_org: (credentials: untyped credentials) -> untyped

      def initialize: (?max_retries: ::Integer max_retries, **untyped args) -> void

      def method_missing: (untyped method_name, *untyped args) { () -> untyped } -> untyped

      def respond_to_missing?: (untyped method_name, ?bool include_private) -> untyped

      def retry_connection_failures: () { () -> untyped } -> untyped
    end
  end
end
