#!/usr/bin/env ruby
# frozen_string_literal: true

tests = Dir["spec/**/*_spec.rb"].
        sort.
        select.
        with_index do |_el, i|
  i % ENV["CI_NODE_TOTAL"].to_i == ENV["CI_NODE_INDEX"].to_i
end

puts "Running the following tests: #{tests.join(' ')}"

exec "bundle exec rspec --profile 10 #{tests.join(' ')}"
