#!/usr/bin/env bash

set -e

bundle install
bundle exec turbo_tests --verbose

# TODO: If you have native helpers or additional tests, add them here
# Example:
# cd /opt/test_overwrite && npm run lint && cd -
# cd /opt/test_overwrite && npm test && cd -
