# typed: strong
# frozen_string_literal: true

require "dependabot/bazel"
require "dependabot/bun"
require "dependabot/bundler"
require "dependabot/cargo"
require "dependabot/composer"
require "dependabot/conda"
require "dependabot/deno"
require "dependabot/devcontainers"
require "dependabot/docker"
require "dependabot/docker_compose"
require "dependabot/dotnet_sdk"
require "dependabot/elm"
require "dependabot/github_actions"
require "dependabot/git_submodules"
require "dependabot/go_modules"
require "dependabot/gradle"
require "dependabot/helm"
require "dependabot/hex"
require "dependabot/julia"
require "dependabot/maven"
require "dependabot/nix"
require "dependabot/npm_and_yarn"
require "dependabot/nuget"
require "dependabot/opentofu"
require "dependabot/pre_commit"
require "dependabot/pub"
require "dependabot/python"
require "dependabot/rust_toolchain"
require "dependabot/swift"
require "dependabot/terraform"
require "dependabot/uv"
require "dependabot/vcpkg"
