name: ARM64 Build
on:  # yamllint disable-line rule:truthy
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  arm64-build:
    runs-on: ubuntu-24.04-arm
    if: github.event_name != 'schedule' || github.repository == 'dependabot/dependabot-core'
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive
          persist-credentials: false

      - name: Build bundler ecosystem image
        run: script/build bundler
