name: Gems - Release to RubyGems
on: # yamllint disable-line rule:truthy
  release:
    # It's fine to trigger on every release because if we tag a release w/o
    # bumping the Gem version, RubyGems will reject it with an error that the
    # version is already live.
    types: [published]
permissions: {}

jobs:
  release-gems:
    name: Release gems to rubygems.org
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          bundler-cache: true

      - name: Install the RubyGems version specified in the Dockerfile.updater-core file
        run: |
          RUBYGEMS_VERSION=$(grep 'ARG RUBYGEMS_VERSION=' Dockerfile.updater-core | cut -d '=' -f 2)
          gem update --system $RUBYGEMS_VERSION

      - name: Install sorbet-runtime for typed code support
        run: |
          SORBET_RUNTIME_VERSION=$(grep 'sorbet-runtime (' Gemfile.lock | grep -v '~>' | grep -v '=' | head -n 1 | sed 's/.*(\(.*\))/\1/')
          gem install sorbet-runtime -v $SORBET_RUNTIME_VERSION

      - uses: rubygems/configure-rubygems-credentials@dc5a8d8553e6ee01fc26761a49e99e733d17954a # v2.1.0

      # We can't use the https://github.com/rubygems/release-gem workflow because it calls `rake release` rather than `rake gems:release`.
      # `rake release` causes problems because it tries to push a git tag, but we've already manually tagged the release as part of the `gems-bump-version` workflow.
      - run: gem exec rake gems:release
