name: Updater-Core image
env:
  UPDATER_CORE_IMAGE: "ghcr.io/dependabot/dependabot-updater-core"
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
permissions: {}

jobs:
  push-updater-core-image:
    name: Push dependabot-updater-core image to GHCR
    runs-on: ubuntu-latest
    if: github.repository == 'dependabot/dependabot-core'
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false

      - uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1

      - name: Build dependabot-updater-core image
        run: script/build common

      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push latest image
        run: |
          docker push "$UPDATER_CORE_IMAGE:latest"
          cosign sign --yes $(cosign triangulate --type=digest "$UPDATER_CORE_IMAGE:latest")

      - name: Push tagged image
        if: contains(github.ref, 'refs/tags')
        run: |
          VERSION="$(grep -Eo "[0-9]+\.[0-9]+\.[0-9]+" common/lib/dependabot.rb)"
          docker tag "$UPDATER_CORE_IMAGE:latest" "$UPDATER_CORE_IMAGE:$VERSION"
          docker push "$UPDATER_CORE_IMAGE:$VERSION"
