name: Pull Request Labeler

on:  # yamllint disable-line rule:truthy
  - pull_request_target

permissions: {}

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
