#!/bin/bash

set -e

if [ -z "$DEPENDABOT_NATIVE_HELPERS_PATH" ]; then
  echo "Unable to build, DEPENDABOT_NATIVE_HELPERS_PATH is not set"
  exit 1
fi

install_dir="$DEPENDABOT_NATIVE_HELPERS_PATH/nuget"

if [ ! -f "$install_dir/helpers/lib/NuGet.Client/NuGet.sln" ]; then
  echo "NuGet.sln not found; please run 'git submodule update --init --recursive' and try again"
  exit 1
fi

os="$(uname -s | tr '[:upper:]' '[:lower:]')"
arch=$(dpkg --print-architecture)
if [ "$arch" = "amd64" ]; then
  arch="x64"
fi

echo "building NuGetUpdater tool"
cd "$install_dir/helpers/lib/NuGetUpdater/NuGetUpdater.Cli"
dotnet publish \
    --configuration Release \
    --output "$install_dir/NuGetUpdater" \
    --framework net7.0 \
    --runtime "$os-$arch"
dotnet clean

echo "verifying NuGetUpdater tool"
"$install_dir/NuGetUpdater/NuGetUpdater.Cli" --version
